import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    arrowParens: "always",
    bracketSameLine: false,
    bracketSpacing: true,
    endOfLine: "lf",
    jsxSingleQuote: false,
    printWidth: 80,
    quoteProps: "as-needed",
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "es5",
    useTabs: false,
    sortImports: {
      ignoreCase: true,
      newlinesBetween: true,
      order: "asc",
    },
    sortPackageJson: true,
    proseWrap: "preserve",
    ignorePatterns: [
      "**/node_modules",
      "**/dist",
      "**/build",
      "**/out",
      "**/coverage",
      "**/.turbo",
      "**/.wrangler",
      "**/_generated",
      "**/generated",
      "**/__generated__",
      "**/*.gen.*",
      "**/*.generated.*",
      "src/mcp/openapi.json",
      "src/mcp/mcp-tools.ts",
      "packages/client/src/types.ts",
      "migrations/**",
      "drizzle/**",
      "**/pnpm-lock.yaml",
      "**/pnpm-workspace.yaml",
      "**/package-lock.json",
      "**/yarn.lock",
    ],
  },
  lint: {
    categories: {
      correctness: "error",
      suspicious: "error",
      perf: "warn",
    },
    options: {
      reportUnusedDisableDirectives: "error",
      typeAware: false,
    },
    ignorePatterns: [
      "**/node_modules",
      "**/dist",
      "**/build",
      "**/out",
      "**/coverage",
      "**/.turbo",
      "**/.wrangler",
      "**/_generated",
      "**/generated",
      "**/__generated__",
      "**/*.gen.*",
      "**/*.generated.*",
      "src/mcp/openapi.json",
      "src/mcp/mcp-tools.ts",
      "packages/client/src/types.ts",
      "migrations/**",
      "drizzle/**",
      "**/worker-configuration.d.ts",
      "**/pnpm-lock.yaml",
      "**/package-lock.json",
      "**/yarn.lock",
    ],
    overrides: [
      {
        files: ["src/mcp/server.ts"],
        rules: {
          "no-map-spread": "off",
        },
      },
      {
        files: [
          "src/migrate/linear.ts",
          "scripts/**",
          "**/*.test.ts",
          "packages/cli/src/index.ts",
        ],
        rules: {
          "no-await-in-loop": "off",
        },
      },
    ],
  },
  test: {
    exclude: ["**/node_modules/**", "**/dist/**", "**/.tmp/**"],
  },
  staged: {
    "*.{js,jsx,ts,tsx}": "vp check --fix --no-error-on-unmatched-pattern",
  },
});
