/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthAcceptInviteRouteImport } from './routes/_auth/accept-invite'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSlugIndexRouteImport } from './routes/_authenticated/$slug/index'
import { Route as AuthenticatedSlugChangelogIndexRouteImport } from './routes/_authenticated/$slug/changelog/index'
import { Route as AuthenticatedSlugCustomersIndexRouteImport } from './routes/_authenticated/$slug/customers/index'
import { Route as AuthenticatedSlugCustomersCustomerIdRouteImport } from './routes/_authenticated/$slug/customers/$customerId'
import { Route as AuthenticatedSlugCyclesIndexRouteImport } from './routes/_authenticated/$slug/cycles/index'
import { Route as AuthenticatedSlugDocumentsIndexRouteImport } from './routes/_authenticated/$slug/documents/index'
import { Route as AuthenticatedSlugDocumentsDocumentIdRouteImport } from './routes/_authenticated/$slug/documents/$documentId'
import { Route as AuthenticatedSlugDocumentsNewRouteImport } from './routes/_authenticated/$slug/documents/new'
import { Route as AuthenticatedSlugInitiativesIndexRouteImport } from './routes/_authenticated/$slug/initiatives/index'
import { Route as AuthenticatedSlugIssuesIndexRouteImport } from './routes/_authenticated/$slug/issues/index'
import { Route as AuthenticatedSlugIssuesIssueIdRouteImport } from './routes/_authenticated/$slug/issues/$issueId'
import { Route as AuthenticatedSlugIssuesNewRouteImport } from './routes/_authenticated/$slug/issues/new'
import { Route as AuthenticatedSlugProjectsIndexRouteImport } from './routes/_authenticated/$slug/projects/index'
import { Route as AuthenticatedSlugProjectsProjectIdRouteImport } from './routes/_authenticated/$slug/projects/$projectId'
import { Route as AuthenticatedSlugRoadmapsIndexRouteImport } from './routes/_authenticated/$slug/roadmaps/index'
import { Route as AuthenticatedSlugSessionsIndexRouteImport } from './routes/_authenticated/$slug/sessions/index'
import { Route as AuthenticatedSlugSessionsSessionIdRouteImport } from './routes/_authenticated/$slug/sessions/$sessionId'
import { Route as AuthenticatedSlugSettingsIndexRouteImport } from './routes/_authenticated/$slug/settings/index'
import { Route as AuthenticatedSlugSettingsAccountRouteImport } from './routes/_authenticated/$slug/settings/account'
import { Route as AuthenticatedSlugSettingsDeveloperRouteImport } from './routes/_authenticated/$slug/settings/developer'
import { Route as AuthenticatedSlugSettingsMembersRouteImport } from './routes/_authenticated/$slug/settings/members'
import { Route as AuthenticatedSlugSettingsSurfacesRouteImport } from './routes/_authenticated/$slug/settings/surfaces'
import { Route as AuthenticatedSlugTicketsIndexRouteImport } from './routes/_authenticated/$slug/tickets/index'
import { Route as AuthenticatedSlugTicketsTicketIdRouteImport } from './routes/_authenticated/$slug/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugIndexRoute = AuthenticatedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugChangelogIndexRoute =
  AuthenticatedSlugChangelogIndexRouteImport.update({
    id: '/changelog/',
    path: '/changelog/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCustomersIndexRoute =
  AuthenticatedSlugCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCustomersCustomerIdRoute =
  AuthenticatedSlugCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCyclesIndexRoute =
  AuthenticatedSlugCyclesIndexRouteImport.update({
    id: '/cycles/',
    path: '/cycles/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocumentsIndexRoute =
  AuthenticatedSlugDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocumentsDocumentIdRoute =
  AuthenticatedSlugDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocumentsNewRoute =
  AuthenticatedSlugDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugInitiativesIndexRoute =
  AuthenticatedSlugInitiativesIndexRouteImport.update({
    id: '/initiatives/',
    path: '/initiatives/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugIssuesIndexRoute =
  AuthenticatedSlugIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugIssuesIssueIdRoute =
  AuthenticatedSlugIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugIssuesNewRoute =
  AuthenticatedSlugIssuesNewRouteImport.update({
    id: '/issues/new',
    path: '/issues/new',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugProjectsIndexRoute =
  AuthenticatedSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugProjectsProjectIdRoute =
  AuthenticatedSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugRoadmapsIndexRoute =
  AuthenticatedSlugRoadmapsIndexRouteImport.update({
    id: '/roadmaps/',
    path: '/roadmaps/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSessionsIndexRoute =
  AuthenticatedSlugSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSessionsSessionIdRoute =
  AuthenticatedSlugSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsIndexRoute =
  AuthenticatedSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsAccountRoute =
  AuthenticatedSlugSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsDeveloperRoute =
  AuthenticatedSlugSettingsDeveloperRouteImport.update({
    id: '/settings/developer',
    path: '/settings/developer',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsMembersRoute =
  AuthenticatedSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsSurfacesRoute =
  AuthenticatedSlugSettingsSurfacesRouteImport.update({
    id: '/settings/surfaces',
    path: '/settings/surfaces',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTicketsIndexRoute =
  AuthenticatedSlugTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTicketsTicketIdRoute =
  AuthenticatedSlugTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/$slug/': typeof AuthenticatedSlugIndexRoute
  '/$slug/customers/$customerId': typeof AuthenticatedSlugCustomersCustomerIdRoute
  '/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/$slug/documents/new': typeof AuthenticatedSlugDocumentsNewRoute
  '/$slug/issues/$issueId': typeof AuthenticatedSlugIssuesIssueIdRoute
  '/$slug/issues/new': typeof AuthenticatedSlugIssuesNewRoute
  '/$slug/projects/$projectId': typeof AuthenticatedSlugProjectsProjectIdRoute
  '/$slug/sessions/$sessionId': typeof AuthenticatedSlugSessionsSessionIdRoute
  '/$slug/settings/account': typeof AuthenticatedSlugSettingsAccountRoute
  '/$slug/settings/developer': typeof AuthenticatedSlugSettingsDeveloperRoute
  '/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/$slug/settings/surfaces': typeof AuthenticatedSlugSettingsSurfacesRoute
  '/$slug/tickets/$ticketId': typeof AuthenticatedSlugTicketsTicketIdRoute
  '/$slug/changelog/': typeof AuthenticatedSlugChangelogIndexRoute
  '/$slug/customers/': typeof AuthenticatedSlugCustomersIndexRoute
  '/$slug/cycles/': typeof AuthenticatedSlugCyclesIndexRoute
  '/$slug/documents/': typeof AuthenticatedSlugDocumentsIndexRoute
  '/$slug/initiatives/': typeof AuthenticatedSlugInitiativesIndexRoute
  '/$slug/issues/': typeof AuthenticatedSlugIssuesIndexRoute
  '/$slug/projects/': typeof AuthenticatedSlugProjectsIndexRoute
  '/$slug/roadmaps/': typeof AuthenticatedSlugRoadmapsIndexRoute
  '/$slug/sessions/': typeof AuthenticatedSlugSessionsIndexRoute
  '/$slug/settings/': typeof AuthenticatedSlugSettingsIndexRoute
  '/$slug/tickets/': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/$slug': typeof AuthenticatedSlugIndexRoute
  '/$slug/customers/$customerId': typeof AuthenticatedSlugCustomersCustomerIdRoute
  '/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/$slug/documents/new': typeof AuthenticatedSlugDocumentsNewRoute
  '/$slug/issues/$issueId': typeof AuthenticatedSlugIssuesIssueIdRoute
  '/$slug/issues/new': typeof AuthenticatedSlugIssuesNewRoute
  '/$slug/projects/$projectId': typeof AuthenticatedSlugProjectsProjectIdRoute
  '/$slug/sessions/$sessionId': typeof AuthenticatedSlugSessionsSessionIdRoute
  '/$slug/settings/account': typeof AuthenticatedSlugSettingsAccountRoute
  '/$slug/settings/developer': typeof AuthenticatedSlugSettingsDeveloperRoute
  '/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/$slug/settings/surfaces': typeof AuthenticatedSlugSettingsSurfacesRoute
  '/$slug/tickets/$ticketId': typeof AuthenticatedSlugTicketsTicketIdRoute
  '/$slug/changelog': typeof AuthenticatedSlugChangelogIndexRoute
  '/$slug/customers': typeof AuthenticatedSlugCustomersIndexRoute
  '/$slug/cycles': typeof AuthenticatedSlugCyclesIndexRoute
  '/$slug/documents': typeof AuthenticatedSlugDocumentsIndexRoute
  '/$slug/initiatives': typeof AuthenticatedSlugInitiativesIndexRoute
  '/$slug/issues': typeof AuthenticatedSlugIssuesIndexRoute
  '/$slug/projects': typeof AuthenticatedSlugProjectsIndexRoute
  '/$slug/roadmaps': typeof AuthenticatedSlugRoadmapsIndexRoute
  '/$slug/sessions': typeof AuthenticatedSlugSessionsIndexRoute
  '/$slug/settings': typeof AuthenticatedSlugSettingsIndexRoute
  '/$slug/tickets': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/accept-invite': typeof AuthAcceptInviteRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/$slug/': typeof AuthenticatedSlugIndexRoute
  '/_authenticated/$slug/customers/$customerId': typeof AuthenticatedSlugCustomersCustomerIdRoute
  '/_authenticated/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/_authenticated/$slug/documents/new': typeof AuthenticatedSlugDocumentsNewRoute
  '/_authenticated/$slug/issues/$issueId': typeof AuthenticatedSlugIssuesIssueIdRoute
  '/_authenticated/$slug/issues/new': typeof AuthenticatedSlugIssuesNewRoute
  '/_authenticated/$slug/projects/$projectId': typeof AuthenticatedSlugProjectsProjectIdRoute
  '/_authenticated/$slug/sessions/$sessionId': typeof AuthenticatedSlugSessionsSessionIdRoute
  '/_authenticated/$slug/settings/account': typeof AuthenticatedSlugSettingsAccountRoute
  '/_authenticated/$slug/settings/developer': typeof AuthenticatedSlugSettingsDeveloperRoute
  '/_authenticated/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/_authenticated/$slug/settings/surfaces': typeof AuthenticatedSlugSettingsSurfacesRoute
  '/_authenticated/$slug/tickets/$ticketId': typeof AuthenticatedSlugTicketsTicketIdRoute
  '/_authenticated/$slug/changelog/': typeof AuthenticatedSlugChangelogIndexRoute
  '/_authenticated/$slug/customers/': typeof AuthenticatedSlugCustomersIndexRoute
  '/_authenticated/$slug/cycles/': typeof AuthenticatedSlugCyclesIndexRoute
  '/_authenticated/$slug/documents/': typeof AuthenticatedSlugDocumentsIndexRoute
  '/_authenticated/$slug/initiatives/': typeof AuthenticatedSlugInitiativesIndexRoute
  '/_authenticated/$slug/issues/': typeof AuthenticatedSlugIssuesIndexRoute
  '/_authenticated/$slug/projects/': typeof AuthenticatedSlugProjectsIndexRoute
  '/_authenticated/$slug/roadmaps/': typeof AuthenticatedSlugRoadmapsIndexRoute
  '/_authenticated/$slug/sessions/': typeof AuthenticatedSlugSessionsIndexRoute
  '/_authenticated/$slug/settings/': typeof AuthenticatedSlugSettingsIndexRoute
  '/_authenticated/$slug/tickets/': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/$slug'
    | '/onboarding'
    | '/$slug/'
    | '/$slug/customers/$customerId'
    | '/$slug/documents/$documentId'
    | '/$slug/documents/new'
    | '/$slug/issues/$issueId'
    | '/$slug/issues/new'
    | '/$slug/projects/$projectId'
    | '/$slug/sessions/$sessionId'
    | '/$slug/settings/account'
    | '/$slug/settings/developer'
    | '/$slug/settings/members'
    | '/$slug/settings/surfaces'
    | '/$slug/tickets/$ticketId'
    | '/$slug/changelog/'
    | '/$slug/customers/'
    | '/$slug/cycles/'
    | '/$slug/documents/'
    | '/$slug/initiatives/'
    | '/$slug/issues/'
    | '/$slug/projects/'
    | '/$slug/roadmaps/'
    | '/$slug/sessions/'
    | '/$slug/settings/'
    | '/$slug/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/onboarding'
    | '/$slug'
    | '/$slug/customers/$customerId'
    | '/$slug/documents/$documentId'
    | '/$slug/documents/new'
    | '/$slug/issues/$issueId'
    | '/$slug/issues/new'
    | '/$slug/projects/$projectId'
    | '/$slug/sessions/$sessionId'
    | '/$slug/settings/account'
    | '/$slug/settings/developer'
    | '/$slug/settings/members'
    | '/$slug/settings/surfaces'
    | '/$slug/tickets/$ticketId'
    | '/$slug/changelog'
    | '/$slug/customers'
    | '/$slug/cycles'
    | '/$slug/documents'
    | '/$slug/initiatives'
    | '/$slug/issues'
    | '/$slug/projects'
    | '/$slug/roadmaps'
    | '/$slug/sessions'
    | '/$slug/settings'
    | '/$slug/tickets'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/accept-invite'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_authenticated/$slug'
    | '/_authenticated/onboarding'
    | '/_authenticated/$slug/'
    | '/_authenticated/$slug/customers/$customerId'
    | '/_authenticated/$slug/documents/$documentId'
    | '/_authenticated/$slug/documents/new'
    | '/_authenticated/$slug/issues/$issueId'
    | '/_authenticated/$slug/issues/new'
    | '/_authenticated/$slug/projects/$projectId'
    | '/_authenticated/$slug/sessions/$sessionId'
    | '/_authenticated/$slug/settings/account'
    | '/_authenticated/$slug/settings/developer'
    | '/_authenticated/$slug/settings/members'
    | '/_authenticated/$slug/settings/surfaces'
    | '/_authenticated/$slug/tickets/$ticketId'
    | '/_authenticated/$slug/changelog/'
    | '/_authenticated/$slug/customers/'
    | '/_authenticated/$slug/cycles/'
    | '/_authenticated/$slug/documents/'
    | '/_authenticated/$slug/initiatives/'
    | '/_authenticated/$slug/issues/'
    | '/_authenticated/$slug/projects/'
    | '/_authenticated/$slug/roadmaps/'
    | '/_authenticated/$slug/sessions/'
    | '/_authenticated/$slug/settings/'
    | '/_authenticated/$slug/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/accept-invite': {
      id: '/_auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug/': {
      id: '/_authenticated/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthenticatedSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/changelog/': {
      id: '/_authenticated/$slug/changelog/'
      path: '/changelog'
      fullPath: '/$slug/changelog/'
      preLoaderRoute: typeof AuthenticatedSlugChangelogIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/customers/': {
      id: '/_authenticated/$slug/customers/'
      path: '/customers'
      fullPath: '/$slug/customers/'
      preLoaderRoute: typeof AuthenticatedSlugCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/customers/$customerId': {
      id: '/_authenticated/$slug/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$slug/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedSlugCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/cycles/': {
      id: '/_authenticated/$slug/cycles/'
      path: '/cycles'
      fullPath: '/$slug/cycles/'
      preLoaderRoute: typeof AuthenticatedSlugCyclesIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents/': {
      id: '/_authenticated/$slug/documents/'
      path: '/documents'
      fullPath: '/$slug/documents/'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents/$documentId': {
      id: '/_authenticated/$slug/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/$slug/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents/new': {
      id: '/_authenticated/$slug/documents/new'
      path: '/documents/new'
      fullPath: '/$slug/documents/new'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/initiatives/': {
      id: '/_authenticated/$slug/initiatives/'
      path: '/initiatives'
      fullPath: '/$slug/initiatives/'
      preLoaderRoute: typeof AuthenticatedSlugInitiativesIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/issues/': {
      id: '/_authenticated/$slug/issues/'
      path: '/issues'
      fullPath: '/$slug/issues/'
      preLoaderRoute: typeof AuthenticatedSlugIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/issues/$issueId': {
      id: '/_authenticated/$slug/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/$slug/issues/$issueId'
      preLoaderRoute: typeof AuthenticatedSlugIssuesIssueIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/issues/new': {
      id: '/_authenticated/$slug/issues/new'
      path: '/issues/new'
      fullPath: '/$slug/issues/new'
      preLoaderRoute: typeof AuthenticatedSlugIssuesNewRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/projects/': {
      id: '/_authenticated/$slug/projects/'
      path: '/projects'
      fullPath: '/$slug/projects/'
      preLoaderRoute: typeof AuthenticatedSlugProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/projects/$projectId': {
      id: '/_authenticated/$slug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$slug/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedSlugProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/roadmaps/': {
      id: '/_authenticated/$slug/roadmaps/'
      path: '/roadmaps'
      fullPath: '/$slug/roadmaps/'
      preLoaderRoute: typeof AuthenticatedSlugRoadmapsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/sessions/': {
      id: '/_authenticated/$slug/sessions/'
      path: '/sessions'
      fullPath: '/$slug/sessions/'
      preLoaderRoute: typeof AuthenticatedSlugSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/sessions/$sessionId': {
      id: '/_authenticated/$slug/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/$slug/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSlugSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/': {
      id: '/_authenticated/$slug/settings/'
      path: '/settings'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof AuthenticatedSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/account': {
      id: '/_authenticated/$slug/settings/account'
      path: '/settings/account'
      fullPath: '/$slug/settings/account'
      preLoaderRoute: typeof AuthenticatedSlugSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/developer': {
      id: '/_authenticated/$slug/settings/developer'
      path: '/settings/developer'
      fullPath: '/$slug/settings/developer'
      preLoaderRoute: typeof AuthenticatedSlugSettingsDeveloperRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/members': {
      id: '/_authenticated/$slug/settings/members'
      path: '/settings/members'
      fullPath: '/$slug/settings/members'
      preLoaderRoute: typeof AuthenticatedSlugSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/surfaces': {
      id: '/_authenticated/$slug/settings/surfaces'
      path: '/settings/surfaces'
      fullPath: '/$slug/settings/surfaces'
      preLoaderRoute: typeof AuthenticatedSlugSettingsSurfacesRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/tickets/': {
      id: '/_authenticated/$slug/tickets/'
      path: '/tickets'
      fullPath: '/$slug/tickets/'
      preLoaderRoute: typeof AuthenticatedSlugTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/tickets/$ticketId': {
      id: '/_authenticated/$slug/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/$slug/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedSlugTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugIndexRoute: typeof AuthenticatedSlugIndexRoute
  AuthenticatedSlugCustomersCustomerIdRoute: typeof AuthenticatedSlugCustomersCustomerIdRoute
  AuthenticatedSlugDocumentsDocumentIdRoute: typeof AuthenticatedSlugDocumentsDocumentIdRoute
  AuthenticatedSlugDocumentsNewRoute: typeof AuthenticatedSlugDocumentsNewRoute
  AuthenticatedSlugIssuesIssueIdRoute: typeof AuthenticatedSlugIssuesIssueIdRoute
  AuthenticatedSlugIssuesNewRoute: typeof AuthenticatedSlugIssuesNewRoute
  AuthenticatedSlugProjectsProjectIdRoute: typeof AuthenticatedSlugProjectsProjectIdRoute
  AuthenticatedSlugSessionsSessionIdRoute: typeof AuthenticatedSlugSessionsSessionIdRoute
  AuthenticatedSlugSettingsAccountRoute: typeof AuthenticatedSlugSettingsAccountRoute
  AuthenticatedSlugSettingsDeveloperRoute: typeof AuthenticatedSlugSettingsDeveloperRoute
  AuthenticatedSlugSettingsMembersRoute: typeof AuthenticatedSlugSettingsMembersRoute
  AuthenticatedSlugSettingsSurfacesRoute: typeof AuthenticatedSlugSettingsSurfacesRoute
  AuthenticatedSlugTicketsTicketIdRoute: typeof AuthenticatedSlugTicketsTicketIdRoute
  AuthenticatedSlugChangelogIndexRoute: typeof AuthenticatedSlugChangelogIndexRoute
  AuthenticatedSlugCustomersIndexRoute: typeof AuthenticatedSlugCustomersIndexRoute
  AuthenticatedSlugCyclesIndexRoute: typeof AuthenticatedSlugCyclesIndexRoute
  AuthenticatedSlugDocumentsIndexRoute: typeof AuthenticatedSlugDocumentsIndexRoute
  AuthenticatedSlugInitiativesIndexRoute: typeof AuthenticatedSlugInitiativesIndexRoute
  AuthenticatedSlugIssuesIndexRoute: typeof AuthenticatedSlugIssuesIndexRoute
  AuthenticatedSlugProjectsIndexRoute: typeof AuthenticatedSlugProjectsIndexRoute
  AuthenticatedSlugRoadmapsIndexRoute: typeof AuthenticatedSlugRoadmapsIndexRoute
  AuthenticatedSlugSessionsIndexRoute: typeof AuthenticatedSlugSessionsIndexRoute
  AuthenticatedSlugSettingsIndexRoute: typeof AuthenticatedSlugSettingsIndexRoute
  AuthenticatedSlugTicketsIndexRoute: typeof AuthenticatedSlugTicketsIndexRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugIndexRoute: AuthenticatedSlugIndexRoute,
  AuthenticatedSlugCustomersCustomerIdRoute:
    AuthenticatedSlugCustomersCustomerIdRoute,
  AuthenticatedSlugDocumentsDocumentIdRoute:
    AuthenticatedSlugDocumentsDocumentIdRoute,
  AuthenticatedSlugDocumentsNewRoute: AuthenticatedSlugDocumentsNewRoute,
  AuthenticatedSlugIssuesIssueIdRoute: AuthenticatedSlugIssuesIssueIdRoute,
  AuthenticatedSlugIssuesNewRoute: AuthenticatedSlugIssuesNewRoute,
  AuthenticatedSlugProjectsProjectIdRoute:
    AuthenticatedSlugProjectsProjectIdRoute,
  AuthenticatedSlugSessionsSessionIdRoute:
    AuthenticatedSlugSessionsSessionIdRoute,
  AuthenticatedSlugSettingsAccountRoute: AuthenticatedSlugSettingsAccountRoute,
  AuthenticatedSlugSettingsDeveloperRoute:
    AuthenticatedSlugSettingsDeveloperRoute,
  AuthenticatedSlugSettingsMembersRoute: AuthenticatedSlugSettingsMembersRoute,
  AuthenticatedSlugSettingsSurfacesRoute:
    AuthenticatedSlugSettingsSurfacesRoute,
  AuthenticatedSlugTicketsTicketIdRoute: AuthenticatedSlugTicketsTicketIdRoute,
  AuthenticatedSlugChangelogIndexRoute: AuthenticatedSlugChangelogIndexRoute,
  AuthenticatedSlugCustomersIndexRoute: AuthenticatedSlugCustomersIndexRoute,
  AuthenticatedSlugCyclesIndexRoute: AuthenticatedSlugCyclesIndexRoute,
  AuthenticatedSlugDocumentsIndexRoute: AuthenticatedSlugDocumentsIndexRoute,
  AuthenticatedSlugInitiativesIndexRoute:
    AuthenticatedSlugInitiativesIndexRoute,
  AuthenticatedSlugIssuesIndexRoute: AuthenticatedSlugIssuesIndexRoute,
  AuthenticatedSlugProjectsIndexRoute: AuthenticatedSlugProjectsIndexRoute,
  AuthenticatedSlugRoadmapsIndexRoute: AuthenticatedSlugRoadmapsIndexRoute,
  AuthenticatedSlugSessionsIndexRoute: AuthenticatedSlugSessionsIndexRoute,
  AuthenticatedSlugSettingsIndexRoute: AuthenticatedSlugSettingsIndexRoute,
  AuthenticatedSlugTicketsIndexRoute: AuthenticatedSlugTicketsIndexRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
