/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSlugIndexRouteImport } from './routes/_authenticated/$slug/index'
import { Route as AuthenticatedSlugCustomersIndexRouteImport } from './routes/_authenticated/$slug/customers/index'
import { Route as AuthenticatedSlugCustomersCustomerIdRouteImport } from './routes/_authenticated/$slug/customers/$customerId'
import { Route as AuthenticatedSlugDocumentsIndexRouteImport } from './routes/_authenticated/$slug/documents/index'
import { Route as AuthenticatedSlugDocumentsDocumentIdRouteImport } from './routes/_authenticated/$slug/documents/$documentId'
import { Route as AuthenticatedSlugDocumentsNewRouteImport } from './routes/_authenticated/$slug/documents/new'
import { Route as AuthenticatedSlugIssuesIndexRouteImport } from './routes/_authenticated/$slug/issues/index'
import { Route as AuthenticatedSlugIssuesIssueIdRouteImport } from './routes/_authenticated/$slug/issues/$issueId'
import { Route as AuthenticatedSlugIssuesNewRouteImport } from './routes/_authenticated/$slug/issues/new'
import { Route as AuthenticatedSlugSettingsAccountRouteImport } from './routes/_authenticated/$slug/settings/account'
import { Route as AuthenticatedSlugSettingsMembersRouteImport } from './routes/_authenticated/$slug/settings/members'
import { Route as AuthenticatedSlugTicketsIndexRouteImport } from './routes/_authenticated/$slug/tickets/index'
import { Route as AuthenticatedSlugTicketsTicketIdRouteImport } from './routes/_authenticated/$slug/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugIndexRoute = AuthenticatedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugCustomersIndexRoute =
  AuthenticatedSlugCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCustomersCustomerIdRoute =
  AuthenticatedSlugCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocumentsIndexRoute =
  AuthenticatedSlugDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocumentsDocumentIdRoute =
  AuthenticatedSlugDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocumentsNewRoute =
  AuthenticatedSlugDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugIssuesIndexRoute =
  AuthenticatedSlugIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugIssuesIssueIdRoute =
  AuthenticatedSlugIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugIssuesNewRoute =
  AuthenticatedSlugIssuesNewRouteImport.update({
    id: '/issues/new',
    path: '/issues/new',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsAccountRoute =
  AuthenticatedSlugSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsMembersRoute =
  AuthenticatedSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTicketsIndexRoute =
  AuthenticatedSlugTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTicketsTicketIdRoute =
  AuthenticatedSlugTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/$slug/': typeof AuthenticatedSlugIndexRoute
  '/$slug/customers/$customerId': typeof AuthenticatedSlugCustomersCustomerIdRoute
  '/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/$slug/documents/new': typeof AuthenticatedSlugDocumentsNewRoute
  '/$slug/issues/$issueId': typeof AuthenticatedSlugIssuesIssueIdRoute
  '/$slug/issues/new': typeof AuthenticatedSlugIssuesNewRoute
  '/$slug/settings/account': typeof AuthenticatedSlugSettingsAccountRoute
  '/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/$slug/tickets/$ticketId': typeof AuthenticatedSlugTicketsTicketIdRoute
  '/$slug/customers/': typeof AuthenticatedSlugCustomersIndexRoute
  '/$slug/documents/': typeof AuthenticatedSlugDocumentsIndexRoute
  '/$slug/issues/': typeof AuthenticatedSlugIssuesIndexRoute
  '/$slug/tickets/': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/$slug': typeof AuthenticatedSlugIndexRoute
  '/$slug/customers/$customerId': typeof AuthenticatedSlugCustomersCustomerIdRoute
  '/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/$slug/documents/new': typeof AuthenticatedSlugDocumentsNewRoute
  '/$slug/issues/$issueId': typeof AuthenticatedSlugIssuesIssueIdRoute
  '/$slug/issues/new': typeof AuthenticatedSlugIssuesNewRoute
  '/$slug/settings/account': typeof AuthenticatedSlugSettingsAccountRoute
  '/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/$slug/tickets/$ticketId': typeof AuthenticatedSlugTicketsTicketIdRoute
  '/$slug/customers': typeof AuthenticatedSlugCustomersIndexRoute
  '/$slug/documents': typeof AuthenticatedSlugDocumentsIndexRoute
  '/$slug/issues': typeof AuthenticatedSlugIssuesIndexRoute
  '/$slug/tickets': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/$slug/': typeof AuthenticatedSlugIndexRoute
  '/_authenticated/$slug/customers/$customerId': typeof AuthenticatedSlugCustomersCustomerIdRoute
  '/_authenticated/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/_authenticated/$slug/documents/new': typeof AuthenticatedSlugDocumentsNewRoute
  '/_authenticated/$slug/issues/$issueId': typeof AuthenticatedSlugIssuesIssueIdRoute
  '/_authenticated/$slug/issues/new': typeof AuthenticatedSlugIssuesNewRoute
  '/_authenticated/$slug/settings/account': typeof AuthenticatedSlugSettingsAccountRoute
  '/_authenticated/$slug/settings/members': typeof AuthenticatedSlugSettingsMembersRoute
  '/_authenticated/$slug/tickets/$ticketId': typeof AuthenticatedSlugTicketsTicketIdRoute
  '/_authenticated/$slug/customers/': typeof AuthenticatedSlugCustomersIndexRoute
  '/_authenticated/$slug/documents/': typeof AuthenticatedSlugDocumentsIndexRoute
  '/_authenticated/$slug/issues/': typeof AuthenticatedSlugIssuesIndexRoute
  '/_authenticated/$slug/tickets/': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/$slug'
    | '/onboarding'
    | '/$slug/'
    | '/$slug/customers/$customerId'
    | '/$slug/documents/$documentId'
    | '/$slug/documents/new'
    | '/$slug/issues/$issueId'
    | '/$slug/issues/new'
    | '/$slug/settings/account'
    | '/$slug/settings/members'
    | '/$slug/tickets/$ticketId'
    | '/$slug/customers/'
    | '/$slug/documents/'
    | '/$slug/issues/'
    | '/$slug/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/onboarding'
    | '/$slug'
    | '/$slug/customers/$customerId'
    | '/$slug/documents/$documentId'
    | '/$slug/documents/new'
    | '/$slug/issues/$issueId'
    | '/$slug/issues/new'
    | '/$slug/settings/account'
    | '/$slug/settings/members'
    | '/$slug/tickets/$ticketId'
    | '/$slug/customers'
    | '/$slug/documents'
    | '/$slug/issues'
    | '/$slug/tickets'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/$slug'
    | '/_authenticated/onboarding'
    | '/_authenticated/$slug/'
    | '/_authenticated/$slug/customers/$customerId'
    | '/_authenticated/$slug/documents/$documentId'
    | '/_authenticated/$slug/documents/new'
    | '/_authenticated/$slug/issues/$issueId'
    | '/_authenticated/$slug/issues/new'
    | '/_authenticated/$slug/settings/account'
    | '/_authenticated/$slug/settings/members'
    | '/_authenticated/$slug/tickets/$ticketId'
    | '/_authenticated/$slug/customers/'
    | '/_authenticated/$slug/documents/'
    | '/_authenticated/$slug/issues/'
    | '/_authenticated/$slug/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug/': {
      id: '/_authenticated/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthenticatedSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/customers/': {
      id: '/_authenticated/$slug/customers/'
      path: '/customers'
      fullPath: '/$slug/customers/'
      preLoaderRoute: typeof AuthenticatedSlugCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/customers/$customerId': {
      id: '/_authenticated/$slug/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$slug/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedSlugCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents/': {
      id: '/_authenticated/$slug/documents/'
      path: '/documents'
      fullPath: '/$slug/documents/'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents/$documentId': {
      id: '/_authenticated/$slug/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/$slug/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents/new': {
      id: '/_authenticated/$slug/documents/new'
      path: '/documents/new'
      fullPath: '/$slug/documents/new'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/issues/': {
      id: '/_authenticated/$slug/issues/'
      path: '/issues'
      fullPath: '/$slug/issues/'
      preLoaderRoute: typeof AuthenticatedSlugIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/issues/$issueId': {
      id: '/_authenticated/$slug/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/$slug/issues/$issueId'
      preLoaderRoute: typeof AuthenticatedSlugIssuesIssueIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/issues/new': {
      id: '/_authenticated/$slug/issues/new'
      path: '/issues/new'
      fullPath: '/$slug/issues/new'
      preLoaderRoute: typeof AuthenticatedSlugIssuesNewRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/account': {
      id: '/_authenticated/$slug/settings/account'
      path: '/settings/account'
      fullPath: '/$slug/settings/account'
      preLoaderRoute: typeof AuthenticatedSlugSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/members': {
      id: '/_authenticated/$slug/settings/members'
      path: '/settings/members'
      fullPath: '/$slug/settings/members'
      preLoaderRoute: typeof AuthenticatedSlugSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/tickets/': {
      id: '/_authenticated/$slug/tickets/'
      path: '/tickets'
      fullPath: '/$slug/tickets/'
      preLoaderRoute: typeof AuthenticatedSlugTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/tickets/$ticketId': {
      id: '/_authenticated/$slug/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/$slug/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedSlugTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugIndexRoute: typeof AuthenticatedSlugIndexRoute
  AuthenticatedSlugCustomersCustomerIdRoute: typeof AuthenticatedSlugCustomersCustomerIdRoute
  AuthenticatedSlugDocumentsDocumentIdRoute: typeof AuthenticatedSlugDocumentsDocumentIdRoute
  AuthenticatedSlugDocumentsNewRoute: typeof AuthenticatedSlugDocumentsNewRoute
  AuthenticatedSlugIssuesIssueIdRoute: typeof AuthenticatedSlugIssuesIssueIdRoute
  AuthenticatedSlugIssuesNewRoute: typeof AuthenticatedSlugIssuesNewRoute
  AuthenticatedSlugSettingsAccountRoute: typeof AuthenticatedSlugSettingsAccountRoute
  AuthenticatedSlugSettingsMembersRoute: typeof AuthenticatedSlugSettingsMembersRoute
  AuthenticatedSlugTicketsTicketIdRoute: typeof AuthenticatedSlugTicketsTicketIdRoute
  AuthenticatedSlugCustomersIndexRoute: typeof AuthenticatedSlugCustomersIndexRoute
  AuthenticatedSlugDocumentsIndexRoute: typeof AuthenticatedSlugDocumentsIndexRoute
  AuthenticatedSlugIssuesIndexRoute: typeof AuthenticatedSlugIssuesIndexRoute
  AuthenticatedSlugTicketsIndexRoute: typeof AuthenticatedSlugTicketsIndexRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugIndexRoute: AuthenticatedSlugIndexRoute,
  AuthenticatedSlugCustomersCustomerIdRoute:
    AuthenticatedSlugCustomersCustomerIdRoute,
  AuthenticatedSlugDocumentsDocumentIdRoute:
    AuthenticatedSlugDocumentsDocumentIdRoute,
  AuthenticatedSlugDocumentsNewRoute: AuthenticatedSlugDocumentsNewRoute,
  AuthenticatedSlugIssuesIssueIdRoute: AuthenticatedSlugIssuesIssueIdRoute,
  AuthenticatedSlugIssuesNewRoute: AuthenticatedSlugIssuesNewRoute,
  AuthenticatedSlugSettingsAccountRoute: AuthenticatedSlugSettingsAccountRoute,
  AuthenticatedSlugSettingsMembersRoute: AuthenticatedSlugSettingsMembersRoute,
  AuthenticatedSlugTicketsTicketIdRoute: AuthenticatedSlugTicketsTicketIdRoute,
  AuthenticatedSlugCustomersIndexRoute: AuthenticatedSlugCustomersIndexRoute,
  AuthenticatedSlugDocumentsIndexRoute: AuthenticatedSlugDocumentsIndexRoute,
  AuthenticatedSlugIssuesIndexRoute: AuthenticatedSlugIssuesIndexRoute,
  AuthenticatedSlugTicketsIndexRoute: AuthenticatedSlugTicketsIndexRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
