import {
  workspaceAgentActivities,
  workspaceAgentSessions,
  workspaceAttachments,
  workspaceComments,
  workspaceDocumentHistory,
  workspaceDocuments,
  workspaceIssueApprovals,
  workspaceIssueHistory,
  workspaceIssueRelations,
  workspaceIssues,
  workspaceIssueSubscribers,
  workspaceLinearUsers,
  workspaceNotifications,
  workspaceOutboundWebhookDeliveries,
  workspaceReactions,
  workspaceSavedViews,
  workspaceUserPreferences,
  workspaceViewFavorites,
  workspaceWebhookSubscriptions,
} from "./schema.js";

export const workspaceSchema = {
  workspaceIssues,
  workspaceIssueHistory,
  workspaceComments,
  workspaceDocuments,
  workspaceDocumentHistory,
  workspaceIssueSubscribers,
  workspaceIssueRelations,
  workspaceIssueApprovals,
  workspaceReactions,
  workspaceAttachments,
  workspaceNotifications,
  workspaceSavedViews,
  workspaceViewFavorites,
  workspaceUserPreferences,
  workspaceLinearUsers,
  workspaceAgentSessions,
  workspaceAgentActivities,
  workspaceWebhookSubscriptions,
  workspaceOutboundWebhookDeliveries,
};
