// Generated by scripts/generate-mcp-tools.ts from src/mcp/openapi.json.
// Do not edit by hand: run `pnpm run mcp:generate`.

export interface McpToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly method: string;
  readonly path: string;
  readonly inputSchema: Record<string, unknown>;
}

export const MCP_TOOLS: readonly McpToolDefinition[] = [
  {
    "name": "deleteWorkspacesOrganizationIdCyclesId",
    "description": "(DELETE /workspaces/{organizationId}/cycles/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesId",
    "description": "(DELETE /workspaces/{organizationId}/issues/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesIssueIdCommentsId",
    "description": "(DELETE /workspaces/{organizationId}/issues/{issueId}/comments/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesIssueIdRelationsId",
    "description": "(DELETE /workspaces/{organizationId}/issues/{issueId}/relations/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{issueId}/relations/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesIssueIdSubscribersId",
    "description": "(DELETE /workspaces/{organizationId}/issues/{issueId}/subscribers/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{issueId}/subscribers/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdLabelsId",
    "description": "(DELETE /workspaces/{organizationId}/labels/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdProjectsId",
    "description": "(DELETE /workspaces/{organizationId}/projects/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdSavedviewsId",
    "description": "(DELETE /workspaces/{organizationId}/saved-views/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdStatesId",
    "description": "(DELETE /workspaces/{organizationId}/states/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdTeamsId",
    "description": "(DELETE /workspaces/{organizationId}/teams/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdTeamsIdMembersMemberId",
    "description": "(DELETE /workspaces/{organizationId}/teams/{id}/members/{memberId})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/teams/{id}/members/{memberId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "memberId": {
          "type": "string"
        },
        "memberType": {
          "type": "string",
          "enum": [
            "user",
            "agent"
          ]
        }
      },
      "required": [
        "id",
        "memberId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdTokensId",
    "description": "(DELETE /workspaces/{organizationId}/tokens/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/tokens/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdWebhooksubscriptionsId",
    "description": "(DELETE /workspaces/{organizationId}/webhook-subscriptions/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspaces",
    "description": "(GET /workspaces)",
    "method": "GET",
    "path": "/workspaces",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "getWorkspacesId",
    "description": "(GET /workspaces/{id})",
    "method": "GET",
    "path": "/workspaces/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdAgentSessions",
    "description": "(GET /workspaces/{organizationId}/agent/sessions)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/agent/sessions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "limit": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdAgentSessionsSessionId",
    "description": "(GET /workspaces/{organizationId}/agent/sessions/{sessionId})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdCycles",
    "description": "(GET /workspaces/{organizationId}/cycles)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/cycles",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdCyclesId",
    "description": "(GET /workspaces/{organizationId}/cycles/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssues",
    "description": "(GET /workspaces/{organizationId}/issues)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "limit": {
          "type": "integer",
          "nullable": true,
          "minimum": 1,
          "maximum": 100
        },
        "cursor": {
          "type": "string"
        },
        "teamId": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "backlog",
            "todo",
            "in_progress",
            "done",
            "canceled"
          ]
        },
        "priority": {
          "type": "string",
          "enum": [
            "low",
            "medium",
            "high",
            "urgent"
          ]
        },
        "assigneeId": {
          "type": "string"
        },
        "projectId": {
          "type": "string"
        },
        "cycleId": {
          "type": "string"
        },
        "labelId": {
          "type": "string"
        },
        "search": {
          "type": "string"
        },
        "identifier": {
          "type": "string"
        },
        "view": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesId",
    "description": "(GET /workspaces/{organizationId}/issues/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdAttachments",
    "description": "(GET /workspaces/{organizationId}/issues/{issueId}/attachments)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/attachments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdComments",
    "description": "(GET /workspaces/{organizationId}/issues/{issueId}/comments)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdCommentsId",
    "description": "(GET /workspaces/{organizationId}/issues/{issueId}/comments/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdHistory",
    "description": "(GET /workspaces/{organizationId}/issues/{issueId}/history)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/history",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdRelations",
    "description": "(GET /workspaces/{organizationId}/issues/{issueId}/relations)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/relations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdSubscribers",
    "description": "(GET /workspaces/{organizationId}/issues/{issueId}/subscribers)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/subscribers",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLabels",
    "description": "(GET /workspaces/{organizationId}/labels)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/labels",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLabelsId",
    "description": "(GET /workspaces/{organizationId}/labels/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLinearusers",
    "description": "(GET /workspaces/{organizationId}/linear-users)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/linear-users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLinearusersLinearId",
    "description": "(GET /workspaces/{organizationId}/linear-users/{linearId})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/linear-users/{linearId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "linearId": {
          "type": "string"
        }
      },
      "required": [
        "linearId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdMemberships",
    "description": "(GET /workspaces/{organizationId}/memberships)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/memberships",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdNotifications",
    "description": "(GET /workspaces/{organizationId}/notifications)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/notifications",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "unreadOnly": {
          "type": "string",
          "description": "Only unread notifications"
        },
        "limit": {
          "type": "string",
          "description": "Max notifications to return"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdNotificationsUnreadcount",
    "description": "(GET /workspaces/{organizationId}/notifications/unread-count)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/notifications/unread-count",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdProjects",
    "description": "(GET /workspaces/{organizationId}/projects)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/projects",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdProjectsId",
    "description": "(GET /workspaces/{organizationId}/projects/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdSavedviews",
    "description": "(GET /workspaces/{organizationId}/saved-views)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/saved-views",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdSavedviewsId",
    "description": "(GET /workspaces/{organizationId}/saved-views/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdStates",
    "description": "(GET /workspaces/{organizationId}/states)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/states",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdStatesId",
    "description": "(GET /workspaces/{organizationId}/states/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTeams",
    "description": "(GET /workspaces/{organizationId}/teams)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTeamsId",
    "description": "(GET /workspaces/{organizationId}/teams/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTeamsIdMembers",
    "description": "(GET /workspaces/{organizationId}/teams/{id}/members)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/teams/{id}/members",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTemplates",
    "description": "(GET /workspaces/{organizationId}/templates)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/templates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTemplatesId",
    "description": "(GET /workspaces/{organizationId}/templates/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/templates/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTokens",
    "description": "(GET /workspaces/{organizationId}/tokens)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/tokens",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdWebhooksubscriptions",
    "description": "(GET /workspaces/{organizationId}/webhook-subscriptions)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/webhook-subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdWebhooksubscriptionsId",
    "description": "(GET /workspaces/{organizationId}/webhook-subscriptions/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdWebhooksubscriptionsIdDeliveries",
    "description": "(GET /workspaces/{organizationId}/webhook-subscriptions/{id}/deliveries)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}/deliveries",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdWs",
    "description": "(GET /workspaces/{organizationId}/ws)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/ws",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesSlugSlug",
    "description": "(GET /workspaces/slug/{slug})",
    "method": "GET",
    "path": "/workspaces/slug/{slug}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "slug": {
          "type": "string"
        }
      },
      "required": [
        "slug"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdAgentSessionsSessionId",
    "description": "(PATCH /workspaces/{organizationId}/agent/sessions/{sessionId})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": [
                "created",
                "running",
                "waiting",
                "completed",
                "failed",
                "canceled"
              ]
            },
            "result": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdCyclesId",
    "description": "(PATCH /workspaces/{organizationId}/cycles/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "projectId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdIssuesId",
    "description": "(PATCH /workspaces/{organizationId}/issues/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "backlog",
                "todo",
                "in_progress",
                "done",
                "canceled"
              ]
            },
            "priority": {
              "type": "string",
              "enum": [
                "low",
                "medium",
                "high",
                "urgent"
              ]
            },
            "assigneeId": {
              "type": "string"
            },
            "projectId": {
              "type": "string"
            },
            "cycleId": {
              "type": "string"
            },
            "labelIds": {
              "type": "string"
            },
            "repo": {
              "type": "string"
            },
            "branch": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdIssuesIssueIdCommentsId",
    "description": "(PATCH /workspaces/{organizationId}/issues/{issueId}/comments/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "body": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "body"
          ]
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdLabelsId",
    "description": "(PATCH /workspaces/{organizationId}/labels/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdNotificationsIdRead",
    "description": "(PATCH /workspaces/{organizationId}/notifications/{id}/read)",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/notifications/{id}/read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdProjectsId",
    "description": "(PATCH /workspaces/{organizationId}/projects/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdSavedviewsId",
    "description": "(PATCH /workspaces/{organizationId}/saved-views/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "filter": {
              "nullable": true
            },
            "search": {
              "type": "string"
            },
            "sort": {
              "type": "object",
              "nullable": true,
              "properties": {
                "field": {
                  "type": "string",
                  "minLength": 1
                },
                "direction": {
                  "type": "string",
                  "enum": [
                    "asc",
                    "desc"
                  ]
                }
              },
              "required": [
                "field"
              ]
            },
            "columns": {
              "type": "array",
              "nullable": true,
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdStatesId",
    "description": "(PATCH /workspaces/{organizationId}/states/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string"
            },
            "color": {
              "type": "string"
            },
            "position": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdTeamsId",
    "description": "(PATCH /workspaces/{organizationId}/teams/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "isPublic": {
              "type": "boolean"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdWebhooksubscriptionsId",
    "description": "(PATCH /workspaces/{organizationId}/webhook-subscriptions/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "events": {
              "type": "string"
            },
            "secret": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspaces",
    "description": "(POST /workspaces)",
    "method": "POST",
    "path": "/workspaces",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "slug": {
              "type": "string",
              "minLength": 1
            },
            "key": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "slug"
          ]
        }
      }
    }
  },
  {
    "name": "postWorkspacesOrganizationIdAgentSessionsSessionIdActivities",
    "description": "(POST /workspaces/{organizationId}/agent/sessions/{sessionId}/activities)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}/activities",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "thought",
                "response",
                "error",
                "elicitation",
                "action",
                "status"
              ]
            },
            "message": {
              "type": "string",
              "minLength": 1
            },
            "payload": {
              "type": "object",
              "additionalProperties": {
                "nullable": true
              }
            }
          },
          "required": [
            "type",
            "message"
          ]
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdAgentSessionsSessionIdPoll",
    "description": "(POST /workspaces/{organizationId}/agent/sessions/{sessionId}/poll)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}/poll",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdCycles",
    "description": "(POST /workspaces/{organizationId}/cycles)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/cycles",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "projectId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdGithubInstall",
    "description": "(POST /workspaces/{organizationId}/github/install)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/github/install",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "installationId": {
              "type": "string"
            }
          },
          "required": [
            "installationId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdGithubUsers",
    "description": "(POST /workspaces/{organizationId}/github/users)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/github/users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "string"
            },
            "githubLogin": {
              "type": "string"
            }
          },
          "required": [
            "userId",
            "githubLogin"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssues",
    "description": "(POST /workspaces/{organizationId}/issues)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "backlog",
                "todo",
                "in_progress",
                "done",
                "canceled"
              ]
            },
            "priority": {
              "type": "string",
              "enum": [
                "low",
                "medium",
                "high",
                "urgent"
              ]
            },
            "assigneeId": {
              "type": "string"
            },
            "projectId": {
              "type": "string"
            },
            "cycleId": {
              "type": "string"
            },
            "labelIds": {
              "type": "string"
            },
            "repo": {
              "type": "string"
            },
            "branch": {
              "type": "string"
            }
          },
          "required": [
            "title"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIdDispatch",
    "description": "(POST /workspaces/{organizationId}/issues/{id}/dispatch)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{id}/dispatch",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "agentId": {
              "type": "string"
            },
            "model": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIssueIdComments",
    "description": "(POST /workspaces/{organizationId}/issues/{issueId}/comments)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "body": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "body"
          ]
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIssueIdRelations",
    "description": "(POST /workspaces/{organizationId}/issues/{issueId}/relations)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{issueId}/relations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "toIssueId": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string",
              "enum": [
                "parent",
                "child",
                "blocks",
                "blocked_by",
                "related",
                "duplicate"
              ]
            }
          },
          "required": [
            "toIssueId",
            "type"
          ]
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIssueIdSubscribers",
    "description": "(POST /workspaces/{organizationId}/issues/{issueId}/subscribers)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{issueId}/subscribers",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearUserId": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "linearUserId"
          ]
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdLabels",
    "description": "(POST /workspaces/{organizationId}/labels)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/labels",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdLinearusers",
    "description": "(POST /workspaces/{organizationId}/linear-users)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/linear-users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string"
            }
          },
          "required": [
            "linearId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdMemberships",
    "description": "(POST /workspaces/{organizationId}/memberships)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/memberships",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "string",
              "minLength": 1
            },
            "role": {
              "type": "string",
              "enum": [
                "owner",
                "admin",
                "member"
              ]
            }
          },
          "required": [
            "userId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdMigrateLinear",
    "description": "(POST /workspaces/{organizationId}/migrate/linear)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/migrate/linear",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearToken": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "linearToken",
            "teamId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdNotificationsMarkallread",
    "description": "(POST /workspaces/{organizationId}/notifications/mark-all-read)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/notifications/mark-all-read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdProjects",
    "description": "(POST /workspaces/{organizationId}/projects)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/projects",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdSavedviews",
    "description": "(POST /workspaces/{organizationId}/saved-views)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/saved-views",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "filter": {
              "nullable": true
            },
            "search": {
              "type": "string"
            },
            "sort": {
              "type": "object",
              "properties": {
                "field": {
                  "type": "string",
                  "minLength": 1
                },
                "direction": {
                  "type": "string",
                  "enum": [
                    "asc",
                    "desc"
                  ]
                }
              },
              "required": [
                "field"
              ]
            },
            "columns": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdStates",
    "description": "(POST /workspaces/{organizationId}/states)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/states",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            },
            "position": {
              "type": "string"
            }
          },
          "required": [
            "linearId",
            "name",
            "type"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTeams",
    "description": "(POST /workspaces/{organizationId}/teams)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "isPublic": {
              "type": "boolean"
            }
          },
          "required": [
            "key",
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTeamsIdMembers",
    "description": "(POST /workspaces/{organizationId}/teams/{id}/members)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/teams/{id}/members",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "memberId": {
              "type": "string"
            },
            "memberType": {
              "type": "string",
              "enum": [
                "user",
                "agent"
              ]
            },
            "role": {
              "type": "string",
              "enum": [
                "member",
                "guest"
              ]
            }
          },
          "required": [
            "memberId",
            "memberType"
          ]
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTemplates",
    "description": "(POST /workspaces/{organizationId}/templates)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/templates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "templateData": {
              "type": "string"
            }
          },
          "required": [
            "linearId",
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTokens",
    "description": "(POST /workspaces/{organizationId}/tokens)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/tokens",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "permissions": {
              "type": "string"
            },
            "actorType": {
              "type": "string",
              "enum": [
                "user",
                "agent"
              ]
            },
            "provider": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdWebhooksubscriptions",
    "description": "(POST /workspaces/{organizationId}/webhook-subscriptions)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/webhook-subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "events": {
              "type": "string"
            },
            "secret": {
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  }
] as const;
