// Generated by scripts/generate-mcp-tools.ts from src/mcp/openapi.json.
// Do not edit by hand: run `pnpm run mcp:generate`.

export interface McpToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly method: string;
  readonly path: string;
  readonly inputSchema: Record<string, unknown>;
}

export const MCP_TOOLS: readonly McpToolDefinition[] = [
  {
    "name": "deleteWorkspacesWorkspaceIdCyclesId",
    "description": "(DELETE /workspaces/{workspaceId}/cycles/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdIssuesId",
    "description": "(DELETE /workspaces/{workspaceId}/issues/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdIssuesIssueIdCommentsId",
    "description": "(DELETE /workspaces/{workspaceId}/issues/{issueId}/comments/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdIssuesIssueIdRelationsId",
    "description": "(DELETE /workspaces/{workspaceId}/issues/{issueId}/relations/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/relations/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdIssuesIssueIdSubscribersId",
    "description": "(DELETE /workspaces/{workspaceId}/issues/{issueId}/subscribers/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/subscribers/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdLabelsId",
    "description": "(DELETE /workspaces/{workspaceId}/labels/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdProjectsId",
    "description": "(DELETE /workspaces/{workspaceId}/projects/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdSavedviewsId",
    "description": "(DELETE /workspaces/{workspaceId}/saved-views/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdStatesId",
    "description": "(DELETE /workspaces/{workspaceId}/states/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdTeamsId",
    "description": "(DELETE /workspaces/{workspaceId}/teams/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdTeamsIdMembersMemberId",
    "description": "(DELETE /workspaces/{workspaceId}/teams/{id}/members/{memberId})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/teams/{id}/members/{memberId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "memberId": {
          "type": "string"
        },
        "memberType": {
          "type": "string",
          "enum": [
            "user",
            "agent"
          ]
        }
      },
      "required": [
        "id",
        "memberId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdTokensId",
    "description": "(DELETE /workspaces/{workspaceId}/tokens/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/tokens/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesWorkspaceIdWebhooksubscriptionsId",
    "description": "(DELETE /workspaces/{workspaceId}/webhook-subscriptions/{id})",
    "method": "DELETE",
    "path": "/workspaces/{workspaceId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspaces",
    "description": "(GET /workspaces)",
    "method": "GET",
    "path": "/workspaces",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "getWorkspacesId",
    "description": "(GET /workspaces/{id})",
    "method": "GET",
    "path": "/workspaces/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "getWorkspacesSlugSlug",
    "description": "(GET /workspaces/slug/{slug})",
    "method": "GET",
    "path": "/workspaces/slug/{slug}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "slug": {
          "type": "string"
        }
      },
      "required": [
        "slug"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdCycles",
    "description": "(GET /workspaces/{workspaceId}/cycles)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/cycles",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdCyclesId",
    "description": "(GET /workspaces/{workspaceId}/cycles/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssues",
    "description": "(GET /workspaces/{workspaceId}/issues)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "limit": {
          "type": "integer",
          "nullable": true,
          "minimum": 1,
          "maximum": 100
        },
        "cursor": {
          "type": "string"
        },
        "teamId": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "backlog",
            "todo",
            "in_progress",
            "done",
            "canceled"
          ]
        },
        "priority": {
          "type": "string",
          "enum": [
            "low",
            "medium",
            "high",
            "urgent"
          ]
        },
        "assigneeId": {
          "type": "string"
        },
        "projectId": {
          "type": "string"
        },
        "cycleId": {
          "type": "string"
        },
        "labelId": {
          "type": "string"
        },
        "search": {
          "type": "string"
        },
        "identifier": {
          "type": "string"
        },
        "view": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssuesId",
    "description": "(GET /workspaces/{workspaceId}/issues/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssuesIssueIdAttachments",
    "description": "(GET /workspaces/{workspaceId}/issues/{issueId}/attachments)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/attachments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssuesIssueIdComments",
    "description": "(GET /workspaces/{workspaceId}/issues/{issueId}/comments)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/comments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssuesIssueIdCommentsId",
    "description": "(GET /workspaces/{workspaceId}/issues/{issueId}/comments/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssuesIssueIdHistory",
    "description": "(GET /workspaces/{workspaceId}/issues/{issueId}/history)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/history",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssuesIssueIdRelations",
    "description": "(GET /workspaces/{workspaceId}/issues/{issueId}/relations)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/relations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdIssuesIssueIdSubscribers",
    "description": "(GET /workspaces/{workspaceId}/issues/{issueId}/subscribers)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/subscribers",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdLabels",
    "description": "(GET /workspaces/{workspaceId}/labels)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/labels",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdLabelsId",
    "description": "(GET /workspaces/{workspaceId}/labels/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdLinearusers",
    "description": "(GET /workspaces/{workspaceId}/linear-users)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/linear-users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdLinearusersLinearId",
    "description": "(GET /workspaces/{workspaceId}/linear-users/{linearId})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/linear-users/{linearId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "linearId": {
          "type": "string"
        }
      },
      "required": [
        "linearId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdMemberships",
    "description": "(GET /workspaces/{workspaceId}/memberships)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/memberships",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdNotifications",
    "description": "(GET /workspaces/{workspaceId}/notifications)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/notifications",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "unreadOnly": {
          "type": "string",
          "description": "Only unread notifications"
        },
        "limit": {
          "type": "string",
          "description": "Max notifications to return"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdNotificationsUnreadcount",
    "description": "(GET /workspaces/{workspaceId}/notifications/unread-count)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/notifications/unread-count",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdProjects",
    "description": "(GET /workspaces/{workspaceId}/projects)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdProjectsId",
    "description": "(GET /workspaces/{workspaceId}/projects/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdSavedviews",
    "description": "(GET /workspaces/{workspaceId}/saved-views)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/saved-views",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdSavedviewsId",
    "description": "(GET /workspaces/{workspaceId}/saved-views/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdStates",
    "description": "(GET /workspaces/{workspaceId}/states)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/states",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdStatesId",
    "description": "(GET /workspaces/{workspaceId}/states/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdTeams",
    "description": "(GET /workspaces/{workspaceId}/teams)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdTeamsId",
    "description": "(GET /workspaces/{workspaceId}/teams/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdTeamsIdMembers",
    "description": "(GET /workspaces/{workspaceId}/teams/{id}/members)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/teams/{id}/members",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdTemplates",
    "description": "(GET /workspaces/{workspaceId}/templates)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/templates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdTemplatesId",
    "description": "(GET /workspaces/{workspaceId}/templates/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/templates/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdTokens",
    "description": "(GET /workspaces/{workspaceId}/tokens)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/tokens",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdWebhooksubscriptions",
    "description": "(GET /workspaces/{workspaceId}/webhook-subscriptions)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/webhook-subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdWebhooksubscriptionsId",
    "description": "(GET /workspaces/{workspaceId}/webhook-subscriptions/{id})",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "getWorkspacesWorkspaceIdWebhooksubscriptionsIdDeliveries",
    "description": "(GET /workspaces/{workspaceId}/webhook-subscriptions/{id}/deliveries)",
    "method": "GET",
    "path": "/workspaces/{workspaceId}/webhook-subscriptions/{id}/deliveries",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdCyclesId",
    "description": "(PATCH /workspaces/{workspaceId}/cycles/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "projectId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdIssuesId",
    "description": "(PATCH /workspaces/{workspaceId}/issues/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "backlog",
                "todo",
                "in_progress",
                "done",
                "canceled"
              ]
            },
            "priority": {
              "type": "string",
              "enum": [
                "low",
                "medium",
                "high",
                "urgent"
              ]
            },
            "assigneeId": {
              "type": "string"
            },
            "projectId": {
              "type": "string"
            },
            "cycleId": {
              "type": "string"
            },
            "labelIds": {
              "type": "string"
            },
            "repo": {
              "type": "string"
            },
            "branch": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdIssuesIssueIdCommentsId",
    "description": "(PATCH /workspaces/{workspaceId}/issues/{issueId}/comments/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "body": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "body"
          ]
        }
      },
      "required": [
        "id",
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdLabelsId",
    "description": "(PATCH /workspaces/{workspaceId}/labels/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdNotificationsIdRead",
    "description": "(PATCH /workspaces/{workspaceId}/notifications/{id}/read)",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/notifications/{id}/read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdProjectsId",
    "description": "(PATCH /workspaces/{workspaceId}/projects/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdSavedviewsId",
    "description": "(PATCH /workspaces/{workspaceId}/saved-views/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "filter": {
              "nullable": true
            },
            "search": {
              "type": "string"
            },
            "sort": {
              "type": "object",
              "nullable": true,
              "properties": {
                "field": {
                  "type": "string",
                  "minLength": 1
                },
                "direction": {
                  "type": "string",
                  "enum": [
                    "asc",
                    "desc"
                  ]
                }
              },
              "required": [
                "field"
              ]
            },
            "columns": {
              "type": "array",
              "nullable": true,
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdStatesId",
    "description": "(PATCH /workspaces/{workspaceId}/states/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string"
            },
            "color": {
              "type": "string"
            },
            "position": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdTeamsId",
    "description": "(PATCH /workspaces/{workspaceId}/teams/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "isPublic": {
              "type": "boolean"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "patchWorkspacesWorkspaceIdWebhooksubscriptionsId",
    "description": "(PATCH /workspaces/{workspaceId}/webhook-subscriptions/{id})",
    "method": "PATCH",
    "path": "/workspaces/{workspaceId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "events": {
              "type": "string"
            },
            "secret": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspaces",
    "description": "(POST /workspaces)",
    "method": "POST",
    "path": "/workspaces",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "slug": {
              "type": "string",
              "minLength": 1
            },
            "key": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "slug"
          ]
        }
      }
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdCycles",
    "description": "(POST /workspaces/{workspaceId}/cycles)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/cycles",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "projectId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdGithubInstall",
    "description": "(POST /workspaces/{workspaceId}/github/install)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/github/install",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "installationId": {
              "type": "string"
            }
          },
          "required": [
            "installationId"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdGithubUsers",
    "description": "(POST /workspaces/{workspaceId}/github/users)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/github/users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "string"
            },
            "githubLogin": {
              "type": "string"
            }
          },
          "required": [
            "userId",
            "githubLogin"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdIssues",
    "description": "(POST /workspaces/{workspaceId}/issues)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/issues",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "backlog",
                "todo",
                "in_progress",
                "done",
                "canceled"
              ]
            },
            "priority": {
              "type": "string",
              "enum": [
                "low",
                "medium",
                "high",
                "urgent"
              ]
            },
            "assigneeId": {
              "type": "string"
            },
            "projectId": {
              "type": "string"
            },
            "cycleId": {
              "type": "string"
            },
            "labelIds": {
              "type": "string"
            },
            "repo": {
              "type": "string"
            },
            "branch": {
              "type": "string"
            }
          },
          "required": [
            "title"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdIssuesIdDispatch",
    "description": "(POST /workspaces/{workspaceId}/issues/{id}/dispatch)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/issues/{id}/dispatch",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "agentId": {
              "type": "string"
            },
            "model": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdIssuesIssueIdComments",
    "description": "(POST /workspaces/{workspaceId}/issues/{issueId}/comments)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/comments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "body": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "body"
          ]
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdIssuesIssueIdRelations",
    "description": "(POST /workspaces/{workspaceId}/issues/{issueId}/relations)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/relations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "toIssueId": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string",
              "enum": [
                "parent",
                "child",
                "blocks",
                "blocked_by",
                "related",
                "duplicate"
              ]
            }
          },
          "required": [
            "toIssueId",
            "type"
          ]
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdIssuesIssueIdSubscribers",
    "description": "(POST /workspaces/{workspaceId}/issues/{issueId}/subscribers)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/issues/{issueId}/subscribers",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearUserId": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "linearUserId"
          ]
        }
      },
      "required": [
        "issueId",
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdLabels",
    "description": "(POST /workspaces/{workspaceId}/labels)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/labels",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdLinearusers",
    "description": "(POST /workspaces/{workspaceId}/linear-users)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/linear-users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string"
            }
          },
          "required": [
            "linearId"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdMemberships",
    "description": "(POST /workspaces/{workspaceId}/memberships)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/memberships",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "string",
              "minLength": 1
            },
            "role": {
              "type": "string",
              "enum": [
                "owner",
                "admin",
                "member"
              ]
            }
          },
          "required": [
            "userId"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdMigrateLinear",
    "description": "(POST /workspaces/{workspaceId}/migrate/linear)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/migrate/linear",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearToken": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "linearToken",
            "teamId"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdNotificationsMarkallread",
    "description": "(POST /workspaces/{workspaceId}/notifications/mark-all-read)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/notifications/mark-all-read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdProjects",
    "description": "(POST /workspaces/{workspaceId}/projects)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/projects",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdSavedviews",
    "description": "(POST /workspaces/{workspaceId}/saved-views)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/saved-views",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "filter": {
              "nullable": true
            },
            "search": {
              "type": "string"
            },
            "sort": {
              "type": "object",
              "properties": {
                "field": {
                  "type": "string",
                  "minLength": 1
                },
                "direction": {
                  "type": "string",
                  "enum": [
                    "asc",
                    "desc"
                  ]
                }
              },
              "required": [
                "field"
              ]
            },
            "columns": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdStates",
    "description": "(POST /workspaces/{workspaceId}/states)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/states",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            },
            "position": {
              "type": "string"
            }
          },
          "required": [
            "linearId",
            "name",
            "type"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdTeams",
    "description": "(POST /workspaces/{workspaceId}/teams)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "isPublic": {
              "type": "boolean"
            }
          },
          "required": [
            "key",
            "name"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdTeamsIdMembers",
    "description": "(POST /workspaces/{workspaceId}/teams/{id}/members)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/teams/{id}/members",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "memberId": {
              "type": "string"
            },
            "memberType": {
              "type": "string",
              "enum": [
                "user",
                "agent"
              ]
            },
            "role": {
              "type": "string",
              "enum": [
                "member",
                "guest"
              ]
            }
          },
          "required": [
            "memberId",
            "memberType"
          ]
        }
      },
      "required": [
        "id",
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdTemplates",
    "description": "(POST /workspaces/{workspaceId}/templates)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/templates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "templateData": {
              "type": "string"
            }
          },
          "required": [
            "linearId",
            "name"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdTokens",
    "description": "(POST /workspaces/{workspaceId}/tokens)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/tokens",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "permissions": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  },
  {
    "name": "postWorkspacesWorkspaceIdWebhooksubscriptions",
    "description": "(POST /workspaces/{workspaceId}/webhook-subscriptions)",
    "method": "POST",
    "path": "/workspaces/{workspaceId}/webhook-subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "workspaceId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "events": {
              "type": "string"
            },
            "secret": {
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        }
      },
      "required": [
        "workspaceId"
      ]
    }
  }
] as const;
