// Generated by scripts/generate-mcp-tools.ts from src/mcp/openapi.json.
// Do not edit by hand: run `pnpm run mcp:generate`.

export interface McpToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly method: string;
  readonly path: string;
  readonly inputSchema: Record<string, unknown>;
}

export const MCP_TOOLS: readonly McpToolDefinition[] = [
  {
    "name": "deleteWorkspacesOrganizationIdCyclesId",
    "description": "Delete cycle (DELETE /workspaces/{organizationId}/cycles/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdInitiativesId",
    "description": "Delete initiative (DELETE /workspaces/{organizationId}/initiatives/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/initiatives/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesId",
    "description": "Delete issue (DELETE /workspaces/{organizationId}/issues/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesIssueIdCommentsId",
    "description": "Delete issue comment (DELETE /workspaces/{organizationId}/issues/{issueId}/comments/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesIssueIdRelationsId",
    "description": "Delete issue relation (DELETE /workspaces/{organizationId}/issues/{issueId}/relations/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{issueId}/relations/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdIssuesIssueIdSubscribersId",
    "description": "Delete issue subscriber (DELETE /workspaces/{organizationId}/issues/{issueId}/subscribers/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/issues/{issueId}/subscribers/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdLabelsId",
    "description": "Delete label (DELETE /workspaces/{organizationId}/labels/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdProjectsId",
    "description": "Delete project (DELETE /workspaces/{organizationId}/projects/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdReactionsReactionId",
    "description": "Delete reaction (DELETE /workspaces/{organizationId}/reactions/{reactionId})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/reactions/{reactionId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "reactionId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId",
        "reactionId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdRoadmapsId",
    "description": "Delete roadmap (DELETE /workspaces/{organizationId}/roadmaps/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/roadmaps/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdSavedviewsId",
    "description": "Delete saved view (DELETE /workspaces/{organizationId}/saved-views/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdStatesId",
    "description": "Delete state (DELETE /workspaces/{organizationId}/states/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdTeamsId",
    "description": "Delete team (DELETE /workspaces/{organizationId}/teams/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdTeamsIdMembersMemberId",
    "description": "Delete team member (DELETE /workspaces/{organizationId}/teams/{id}/members/{memberId})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/teams/{id}/members/{memberId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "memberId": {
          "type": "string"
        },
        "memberType": {
          "type": "string",
          "enum": [
            "user",
            "agent"
          ]
        }
      },
      "required": [
        "id",
        "memberId",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdTokensId",
    "description": "Delete token (DELETE /workspaces/{organizationId}/tokens/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/tokens/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "deleteWorkspacesOrganizationIdWebhooksubscriptionsId",
    "description": "Delete webhook subscription (DELETE /workspaces/{organizationId}/webhook-subscriptions/{id})",
    "method": "DELETE",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspaces",
    "description": "List workspaces (GET /workspaces)",
    "method": "GET",
    "path": "/workspaces",
    "inputSchema": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "getWorkspacesId",
    "description": "Get workspace (GET /workspaces/{id})",
    "method": "GET",
    "path": "/workspaces/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdAgentSessions",
    "description": "List agent sessions (GET /workspaces/{organizationId}/agent/sessions)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/agent/sessions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "limit": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdAgentSessionsSessionId",
    "description": "Get agent session (GET /workspaces/{organizationId}/agent/sessions/{sessionId})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdCommentsCommentIdReactions",
    "description": "List comment reactions (GET /workspaces/{organizationId}/comments/{commentId}/reactions)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/comments/{commentId}/reactions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "commentId": {
          "type": "string"
        }
      },
      "required": [
        "commentId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdCycles",
    "description": "List cycles (GET /workspaces/{organizationId}/cycles)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/cycles",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdCyclesId",
    "description": "Get cycle (GET /workspaces/{organizationId}/cycles/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdInitiatives",
    "description": "List initiatives (GET /workspaces/{organizationId}/initiatives)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/initiatives",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "roadmapId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdInitiativesId",
    "description": "Get initiative (GET /workspaces/{organizationId}/initiatives/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/initiatives/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssues",
    "description": "List issues (GET /workspaces/{organizationId}/issues)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "limit": {
          "type": "integer",
          "nullable": true,
          "minimum": 1,
          "maximum": 100
        },
        "cursor": {
          "type": "string"
        },
        "teamId": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "triage",
            "backlog",
            "todo",
            "in_progress",
            "done",
            "canceled"
          ]
        },
        "priority": {
          "type": "string",
          "enum": [
            "low",
            "medium",
            "high",
            "urgent"
          ]
        },
        "parentId": {
          "type": "string"
        },
        "hasParent": {
          "type": "string",
          "enum": [
            "true",
            "false"
          ]
        },
        "isParent": {
          "type": "string",
          "enum": [
            "true",
            "false"
          ]
        },
        "assigneeId": {
          "type": "string"
        },
        "projectId": {
          "type": "string"
        },
        "cycleId": {
          "type": "string"
        },
        "labelId": {
          "type": "string"
        },
        "search": {
          "type": "string"
        },
        "identifier": {
          "type": "string"
        },
        "view": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesId",
    "description": "Get issue (GET /workspaces/{organizationId}/issues/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIdChildren",
    "description": "List issue children (GET /workspaces/{organizationId}/issues/{id}/children)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{id}/children",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIdReactions",
    "description": "List issue reactions (GET /workspaces/{organizationId}/issues/{id}/reactions)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{id}/reactions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdAttachments",
    "description": "List issue attachments (GET /workspaces/{organizationId}/issues/{issueId}/attachments)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/attachments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdComments",
    "description": "List issue comments (GET /workspaces/{organizationId}/issues/{issueId}/comments)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdCommentsId",
    "description": "Get issue comment (GET /workspaces/{organizationId}/issues/{issueId}/comments/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdHistory",
    "description": "List issue history (GET /workspaces/{organizationId}/issues/{issueId}/history)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/history",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdRelations",
    "description": "List issue relations (GET /workspaces/{organizationId}/issues/{issueId}/relations)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/relations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "direction": {
          "type": "string",
          "enum": [
            "outgoing",
            "incoming"
          ]
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdIssuesIssueIdSubscribers",
    "description": "List issue subscribers (GET /workspaces/{organizationId}/issues/{issueId}/subscribers)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/issues/{issueId}/subscribers",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLabels",
    "description": "List labels (GET /workspaces/{organizationId}/labels)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/labels",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLabelsId",
    "description": "Get label (GET /workspaces/{organizationId}/labels/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLinearusers",
    "description": "List linear users (GET /workspaces/{organizationId}/linear-users)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/linear-users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdLinearusersLinearId",
    "description": "Get linear user (GET /workspaces/{organizationId}/linear-users/{linearId})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/linear-users/{linearId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "linearId": {
          "type": "string"
        }
      },
      "required": [
        "linearId",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdMemberships",
    "description": "List memberships (GET /workspaces/{organizationId}/memberships)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/memberships",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdNotifications",
    "description": "List notifications (GET /workspaces/{organizationId}/notifications)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/notifications",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "unreadOnly": {
          "type": "string",
          "description": "Only unread notifications"
        },
        "limit": {
          "type": "string",
          "description": "Max notifications to return"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdNotificationsUnreadcount",
    "description": "Get unread notification count (GET /workspaces/{organizationId}/notifications/unread-count)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/notifications/unread-count",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdProjects",
    "description": "List projects (GET /workspaces/{organizationId}/projects)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/projects",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdProjectsId",
    "description": "Get project (GET /workspaces/{organizationId}/projects/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdRoadmaps",
    "description": "List roadmaps (GET /workspaces/{organizationId}/roadmaps)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/roadmaps",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdRoadmapsId",
    "description": "Get roadmap (GET /workspaces/{organizationId}/roadmaps/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/roadmaps/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdRoadmapsIdInitiatives",
    "description": "List roadmap initiatives (GET /workspaces/{organizationId}/roadmaps/{id}/initiatives)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/roadmaps/{id}/initiatives",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdSavedviews",
    "description": "List saved views (GET /workspaces/{organizationId}/saved-views)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/saved-views",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdSavedviewsId",
    "description": "Get saved view (GET /workspaces/{organizationId}/saved-views/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdStates",
    "description": "List states (GET /workspaces/{organizationId}/states)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/states",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdStatesId",
    "description": "Get state (GET /workspaces/{organizationId}/states/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTeams",
    "description": "List teams (GET /workspaces/{organizationId}/teams)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTeamsId",
    "description": "Get team (GET /workspaces/{organizationId}/teams/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTeamsIdMembers",
    "description": "List team members (GET /workspaces/{organizationId}/teams/{id}/members)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/teams/{id}/members",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTemplates",
    "description": "List templates (GET /workspaces/{organizationId}/templates)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/templates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTemplatesId",
    "description": "Get template (GET /workspaces/{organizationId}/templates/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/templates/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdTokens",
    "description": "List tokens (GET /workspaces/{organizationId}/tokens)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/tokens",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdWebhooksubscriptions",
    "description": "List webhook subscriptions (GET /workspaces/{organizationId}/webhook-subscriptions)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/webhook-subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdWebhooksubscriptionsId",
    "description": "Get webhook subscription (GET /workspaces/{organizationId}/webhook-subscriptions/{id})",
    "method": "GET",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesOrganizationIdWebhooksubscriptionsIdDeliveries",
    "description": "List webhook subscription deliveries (GET /workspaces/{organizationId}/webhook-subscriptions/{id}/deliveries)",
    "method": "GET",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}/deliveries",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "getWorkspacesSlugSlug",
    "description": "Get workspace by slug (GET /workspaces/slug/{slug})",
    "method": "GET",
    "path": "/workspaces/slug/{slug}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "slug": {
          "type": "string"
        }
      },
      "required": [
        "slug"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdAgentSessionsSessionId",
    "description": "Update agent session (PATCH /workspaces/{organizationId}/agent/sessions/{sessionId})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": [
                "created",
                "running",
                "waiting",
                "completed",
                "failed",
                "canceled"
              ]
            },
            "result": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdCyclesId",
    "description": "Update cycle (PATCH /workspaces/{organizationId}/cycles/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/cycles/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "projectId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdInitiativesId",
    "description": "Update initiative (PATCH /workspaces/{organizationId}/initiatives/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/initiatives/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "roadmapId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "targetDate": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdIssuesId",
    "description": "Update issue (PATCH /workspaces/{organizationId}/issues/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/issues/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "triage",
                "backlog",
                "todo",
                "in_progress",
                "done",
                "canceled"
              ]
            },
            "priority": {
              "type": "string",
              "enum": [
                "low",
                "medium",
                "high",
                "urgent"
              ]
            },
            "resolution": {
              "type": "string",
              "nullable": true,
              "enum": [
                "duplicate",
                "not_planned",
                "intended_behavior",
                "not_reproducible",
                "obsolete",
                "resolved",
                null
              ]
            },
            "parentId": {
              "type": "string",
              "nullable": true
            },
            "subIssueSortOrder": {
              "type": "number",
              "nullable": true
            },
            "assigneeId": {
              "type": "string"
            },
            "projectId": {
              "type": "string"
            },
            "cycleId": {
              "type": "string"
            },
            "labelIds": {
              "type": "string"
            },
            "repo": {
              "type": "string"
            },
            "branch": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdIssuesIssueIdCommentsId",
    "description": "Update issue comment (PATCH /workspaces/{organizationId}/issues/{issueId}/comments/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "body": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "body"
          ]
        }
      },
      "required": [
        "id",
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdLabelsId",
    "description": "Update label (PATCH /workspaces/{organizationId}/labels/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/labels/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdNotificationsIdRead",
    "description": "Mark notification as read (PATCH /workspaces/{organizationId}/notifications/{id}/read)",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/notifications/{id}/read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdProjectsId",
    "description": "Update project (PATCH /workspaces/{organizationId}/projects/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/projects/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdRoadmapsId",
    "description": "Update roadmap (PATCH /workspaces/{organizationId}/roadmaps/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/roadmaps/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdSavedviewsId",
    "description": "Update saved view (PATCH /workspaces/{organizationId}/saved-views/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/saved-views/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "filter": {
              "nullable": true
            },
            "search": {
              "type": "string"
            },
            "sort": {
              "type": "object",
              "nullable": true,
              "properties": {
                "field": {
                  "type": "string",
                  "minLength": 1
                },
                "direction": {
                  "type": "string",
                  "enum": [
                    "asc",
                    "desc"
                  ]
                }
              },
              "required": [
                "field"
              ]
            },
            "columns": {
              "type": "array",
              "nullable": true,
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdStatesId",
    "description": "Update state (PATCH /workspaces/{organizationId}/states/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/states/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string"
            },
            "color": {
              "type": "string"
            },
            "position": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdTeamsId",
    "description": "Update team (PATCH /workspaces/{organizationId}/teams/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "isPublic": {
              "type": "boolean"
            },
            "parentAutoClose": {
              "type": "boolean"
            },
            "subIssueAutoClose": {
              "type": "boolean"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "patchWorkspacesOrganizationIdWebhooksubscriptionsId",
    "description": "Update webhook subscription (PATCH /workspaces/{organizationId}/webhook-subscriptions/{id})",
    "method": "PATCH",
    "path": "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "events": {
              "type": "string"
            },
            "secret": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspaces",
    "description": "Create workspace (POST /workspaces)",
    "method": "POST",
    "path": "/workspaces",
    "inputSchema": {
      "type": "object",
      "properties": {
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "slug": {
              "type": "string",
              "minLength": 1
            },
            "key": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "slug"
          ]
        }
      }
    }
  },
  {
    "name": "postWorkspacesOrganizationIdAgentSessionsSessionIdActivities",
    "description": "Create agent session activity (POST /workspaces/{organizationId}/agent/sessions/{sessionId}/activities)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}/activities",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "thought",
                "response",
                "error",
                "elicitation",
                "action",
                "status"
              ]
            },
            "message": {
              "type": "string",
              "minLength": 1
            },
            "payload": {
              "type": "object",
              "additionalProperties": {
                "nullable": true
              }
            }
          },
          "required": [
            "type",
            "message"
          ]
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdAgentSessionsSessionIdPoll",
    "description": "Poll agent session (POST /workspaces/{organizationId}/agent/sessions/{sessionId}/poll)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/agent/sessions/{sessionId}/poll",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId",
        "sessionId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdCommentsCommentIdReactions",
    "description": "Create comment reaction (POST /workspaces/{organizationId}/comments/{commentId}/reactions)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/comments/{commentId}/reactions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "commentId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "emoji": {
              "type": "string",
              "minLength": 1,
              "maxLength": 8
            }
          },
          "required": [
            "emoji"
          ]
        }
      },
      "required": [
        "commentId",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdCycles",
    "description": "Create cycle (POST /workspaces/{organizationId}/cycles)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/cycles",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "projectId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdGithubInstall",
    "description": "Install GitHub app (POST /workspaces/{organizationId}/github/install)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/github/install",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "installationId": {
              "type": "string"
            }
          },
          "required": [
            "installationId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdGithubUsers",
    "description": "Sync GitHub users (POST /workspaces/{organizationId}/github/users)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/github/users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "string"
            },
            "githubLogin": {
              "type": "string"
            }
          },
          "required": [
            "userId",
            "githubLogin"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdInitiatives",
    "description": "Create initiative (POST /workspaces/{organizationId}/initiatives)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/initiatives",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "roadmapId": {
              "type": "string"
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "targetDate": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssues",
    "description": "Create issue (POST /workspaces/{organizationId}/issues)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "triage",
                "backlog",
                "todo",
                "in_progress",
                "done",
                "canceled"
              ]
            },
            "priority": {
              "type": "string",
              "enum": [
                "low",
                "medium",
                "high",
                "urgent"
              ]
            },
            "resolution": {
              "type": "string",
              "nullable": true,
              "enum": [
                "duplicate",
                "not_planned",
                "intended_behavior",
                "not_reproducible",
                "obsolete",
                "resolved",
                null
              ]
            },
            "parentId": {
              "type": "string",
              "nullable": true
            },
            "subIssueSortOrder": {
              "type": "number",
              "nullable": true
            },
            "assigneeId": {
              "type": "string"
            },
            "projectId": {
              "type": "string"
            },
            "cycleId": {
              "type": "string"
            },
            "labelIds": {
              "type": "string"
            },
            "repo": {
              "type": "string"
            },
            "branch": {
              "type": "string"
            }
          },
          "required": [
            "title"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesBatch",
    "description": "Create issue batch (POST /workspaces/{organizationId}/issues/batch)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/batch",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "ids": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              },
              "minItems": 1,
              "maxItems": 100
            },
            "patch": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "minLength": 1
                },
                "teamId": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "status": {
                  "type": "string",
                  "enum": [
                    "triage",
                    "backlog",
                    "todo",
                    "in_progress",
                    "done",
                    "canceled"
                  ]
                },
                "priority": {
                  "type": "string",
                  "enum": [
                    "low",
                    "medium",
                    "high",
                    "urgent"
                  ]
                },
                "resolution": {
                  "type": "string",
                  "nullable": true,
                  "enum": [
                    "duplicate",
                    "not_planned",
                    "intended_behavior",
                    "not_reproducible",
                    "obsolete",
                    "resolved",
                    null
                  ]
                },
                "parentId": {
                  "type": "string",
                  "nullable": true
                },
                "subIssueSortOrder": {
                  "type": "number",
                  "nullable": true
                },
                "assigneeId": {
                  "type": "string"
                },
                "projectId": {
                  "type": "string"
                },
                "cycleId": {
                  "type": "string"
                },
                "labelIds": {
                  "type": "string"
                },
                "repo": {
                  "type": "string"
                },
                "branch": {
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "ids",
            "patch"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIdDispatch",
    "description": "Dispatch issue (POST /workspaces/{organizationId}/issues/{id}/dispatch)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{id}/dispatch",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "agentId": {
              "type": "string"
            },
            "model": {
              "type": "string"
            }
          }
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIdReactions",
    "description": "Create issue reaction (POST /workspaces/{organizationId}/issues/{id}/reactions)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{id}/reactions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "emoji": {
              "type": "string",
              "minLength": 1,
              "maxLength": 8
            }
          },
          "required": [
            "emoji"
          ]
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIssueIdComments",
    "description": "Create issue comment (POST /workspaces/{organizationId}/issues/{issueId}/comments)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{issueId}/comments",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "body": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "body"
          ]
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIssueIdRelations",
    "description": "Create issue relation (POST /workspaces/{organizationId}/issues/{issueId}/relations)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{issueId}/relations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "toIssueId": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string",
              "enum": [
                "related",
                "blocks",
                "duplicate",
                "similar"
              ]
            }
          },
          "required": [
            "toIssueId",
            "type"
          ]
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdIssuesIssueIdSubscribers",
    "description": "Create issue subscriber (POST /workspaces/{organizationId}/issues/{issueId}/subscribers)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/issues/{issueId}/subscribers",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearUserId": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "linearUserId"
          ]
        }
      },
      "required": [
        "issueId",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdLabels",
    "description": "Create label (POST /workspaces/{organizationId}/labels)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/labels",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdLinearusers",
    "description": "Create linear user (POST /workspaces/{organizationId}/linear-users)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/linear-users",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string"
            }
          },
          "required": [
            "linearId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdMemberships",
    "description": "Create membership (POST /workspaces/{organizationId}/memberships)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/memberships",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "string",
              "minLength": 1
            },
            "role": {
              "type": "string",
              "enum": [
                "owner",
                "admin",
                "member"
              ]
            }
          },
          "required": [
            "userId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdMigrateLinear",
    "description": "Migrate from Linear (POST /workspaces/{organizationId}/migrate/linear)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/migrate/linear",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearToken": {
              "type": "string",
              "minLength": 1
            },
            "teamId": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": [
            "linearToken",
            "teamId"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdNotificationsMarkallread",
    "description": "Mark all notifications as read (POST /workspaces/{organizationId}/notifications/mark-all-read)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/notifications/mark-all-read",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdProjects",
    "description": "Create project (POST /workspaces/{organizationId}/projects)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/projects",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "startDate": {
              "type": "string"
            },
            "endDate": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdRoadmaps",
    "description": "Create roadmap (POST /workspaces/{organizationId}/roadmaps)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/roadmaps",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdSavedviews",
    "description": "Create saved view (POST /workspaces/{organizationId}/saved-views)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/saved-views",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "filter": {
              "nullable": true
            },
            "search": {
              "type": "string"
            },
            "sort": {
              "type": "object",
              "properties": {
                "field": {
                  "type": "string",
                  "minLength": 1
                },
                "direction": {
                  "type": "string",
                  "enum": [
                    "asc",
                    "desc"
                  ]
                }
              },
              "required": [
                "field"
              ]
            },
            "columns": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdStates",
    "description": "Create state (POST /workspaces/{organizationId}/states)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/states",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "type": {
              "type": "string",
              "minLength": 1
            },
            "color": {
              "type": "string"
            },
            "position": {
              "type": "string"
            }
          },
          "required": [
            "linearId",
            "name",
            "type"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTeams",
    "description": "Create team (POST /workspaces/{organizationId}/teams)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "isPublic": {
              "type": "boolean"
            },
            "parentAutoClose": {
              "type": "boolean"
            },
            "subIssueAutoClose": {
              "type": "boolean"
            }
          },
          "required": [
            "key",
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTeamsIdMembers",
    "description": "Create team member (POST /workspaces/{organizationId}/teams/{id}/members)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/teams/{id}/members",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "memberId": {
              "type": "string"
            },
            "memberType": {
              "type": "string",
              "enum": [
                "user",
                "agent"
              ]
            },
            "role": {
              "type": "string",
              "enum": [
                "member",
                "guest"
              ]
            }
          },
          "required": [
            "memberId",
            "memberType"
          ]
        }
      },
      "required": [
        "id",
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTemplates",
    "description": "Create template (POST /workspaces/{organizationId}/templates)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/templates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "linearId": {
              "type": "string",
              "minLength": 1
            },
            "name": {
              "type": "string",
              "minLength": 1
            },
            "templateData": {
              "type": "string"
            }
          },
          "required": [
            "linearId",
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdTokens",
    "description": "Create token (POST /workspaces/{organizationId}/tokens)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/tokens",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "minLength": 1
            },
            "permissions": {
              "type": "string"
            },
            "actorType": {
              "type": "string",
              "enum": [
                "user",
                "agent"
              ]
            },
            "provider": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  },
  {
    "name": "postWorkspacesOrganizationIdWebhooksubscriptions",
    "description": "Create webhook subscription (POST /workspaces/{organizationId}/webhook-subscriptions)",
    "method": "POST",
    "path": "/workspaces/{organizationId}/webhook-subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "body": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "events": {
              "type": "string"
            },
            "secret": {
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        }
      },
      "required": [
        "organizationId"
      ]
    }
  }
] as const;
