// Generated by scripts/generate-cli.ts from src/mcp/openapi.json.
// Do not edit by hand: run `pnpm run cli:generate`.

export interface CommandDef {
  readonly method: string;
  readonly path: string;
  readonly params: readonly { name: string; flag: string }[];
  readonly query: readonly { name: string; flag: string }[];
  readonly body: readonly { name: string; flag: string }[];
}

export const COMMANDS: Record<string, CommandDef> = {
  "workspaces list": {
    method: "GET",
    path: "/workspaces",
    params: [],
    query: [],
    body: [],
  },
  "workspaces create": {
    method: "POST",
    path: "/workspaces",
    params: [],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "slug",
        flag: "slug",
      },
      {
        name: "key",
        flag: "key",
      },
    ],
  },
  "workspaces get": {
    method: "GET",
    path: "/workspaces/{id}",
    params: [
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "workspaces slug": {
    method: "GET",
    path: "/workspaces/slug/{slug}",
    params: [
      {
        name: "slug",
        flag: "slug",
      },
    ],
    query: [],
    body: [],
  },
  "tokens list": {
    method: "GET",
    path: "/workspaces/{organizationId}/tokens",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "tokens create": {
    method: "POST",
    path: "/workspaces/{organizationId}/tokens",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "permissions",
        flag: "permissions",
      },
      {
        name: "actorType",
        flag: "actor-type",
      },
      {
        name: "provider",
        flag: "provider",
      },
    ],
  },
  "tokens delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/tokens/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues list": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [
      {
        name: "limit",
        flag: "limit",
      },
      {
        name: "cursor",
        flag: "cursor",
      },
      {
        name: "teamId",
        flag: "team",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "priority",
        flag: "priority",
      },
      {
        name: "parentId",
        flag: "parent",
      },
      {
        name: "hasParent",
        flag: "has-parent",
      },
      {
        name: "isParent",
        flag: "is-parent",
      },
      {
        name: "isDraft",
        flag: "is-draft",
      },
      {
        name: "includeSnoozed",
        flag: "include-snoozed",
      },
      {
        name: "assigneeId",
        flag: "assignee",
      },
      {
        name: "projectId",
        flag: "project",
      },
      {
        name: "cycleId",
        flag: "cycle",
      },
      {
        name: "labelId",
        flag: "label",
      },
      {
        name: "search",
        flag: "search",
      },
      {
        name: "identifier",
        flag: "identifier",
      },
      {
        name: "view",
        flag: "view",
      },
    ],
    body: [],
  },
  "issues create": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "title",
        flag: "title",
      },
      {
        name: "teamId",
        flag: "team",
      },
      {
        name: "description",
        flag: "description",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "priority",
        flag: "priority",
      },
      {
        name: "resolution",
        flag: "resolution",
      },
      {
        name: "parentId",
        flag: "parent",
      },
      {
        name: "subIssueSortOrder",
        flag: "sub-issue-sort-order",
      },
      {
        name: "estimate",
        flag: "estimate",
      },
      {
        name: "isDraft",
        flag: "is-draft",
      },
      {
        name: "templateId",
        flag: "template",
      },
      {
        name: "snoozedUntil",
        flag: "snoozed-until",
      },
      {
        name: "assigneeId",
        flag: "assignee",
      },
      {
        name: "projectId",
        flag: "project",
      },
      {
        name: "cycleId",
        flag: "cycle",
      },
      {
        name: "labelIds",
        flag: "label-ids",
      },
      {
        name: "repo",
        flag: "repo",
      },
      {
        name: "branch",
        flag: "branch",
      },
    ],
  },
  "issue analytics list": {
    method: "GET",
    path: "/workspaces/{organizationId}/issue-analytics",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [
      {
        name: "groupBy",
        flag: "group-by",
      },
    ],
    body: [],
  },
  "issue analytics burndown list": {
    method: "GET",
    path: "/workspaces/{organizationId}/issue-analytics/burndown",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [
      {
        name: "cycleId",
        flag: "cycle",
      },
    ],
    body: [],
  },
  "triage list": {
    method: "GET",
    path: "/workspaces/{organizationId}/triage",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [
      {
        name: "limit",
        flag: "limit",
      },
      {
        name: "cursor",
        flag: "cursor",
      },
      {
        name: "teamId",
        flag: "team",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "priority",
        flag: "priority",
      },
      {
        name: "parentId",
        flag: "parent",
      },
      {
        name: "hasParent",
        flag: "has-parent",
      },
      {
        name: "isParent",
        flag: "is-parent",
      },
      {
        name: "isDraft",
        flag: "is-draft",
      },
      {
        name: "includeSnoozed",
        flag: "include-snoozed",
      },
      {
        name: "assigneeId",
        flag: "assignee",
      },
      {
        name: "projectId",
        flag: "project",
      },
      {
        name: "cycleId",
        flag: "cycle",
      },
      {
        name: "labelId",
        flag: "label",
      },
      {
        name: "search",
        flag: "search",
      },
      {
        name: "identifier",
        flag: "identifier",
      },
      {
        name: "view",
        flag: "view",
      },
    ],
    body: [],
  },
  "issues get": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/issues/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "title",
        flag: "title",
      },
      {
        name: "teamId",
        flag: "team",
      },
      {
        name: "description",
        flag: "description",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "priority",
        flag: "priority",
      },
      {
        name: "resolution",
        flag: "resolution",
      },
      {
        name: "parentId",
        flag: "parent",
      },
      {
        name: "subIssueSortOrder",
        flag: "sub-issue-sort-order",
      },
      {
        name: "estimate",
        flag: "estimate",
      },
      {
        name: "isDraft",
        flag: "is-draft",
      },
      {
        name: "templateId",
        flag: "template",
      },
      {
        name: "snoozedUntil",
        flag: "snoozed-until",
      },
      {
        name: "assigneeId",
        flag: "assignee",
      },
      {
        name: "projectId",
        flag: "project",
      },
      {
        name: "cycleId",
        flag: "cycle",
      },
      {
        name: "labelIds",
        flag: "label-ids",
      },
      {
        name: "repo",
        flag: "repo",
      },
      {
        name: "branch",
        flag: "branch",
      },
    ],
  },
  "issues delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/issues/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues children list": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues/{id}/children",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues batch": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues/batch",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "ids",
        flag: "ids",
      },
      {
        name: "patch",
        flag: "patch",
      },
    ],
  },
  "issues dispatch": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues/{id}/dispatch",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "agentId",
        flag: "agent-id",
      },
      {
        name: "model",
        flag: "model",
      },
    ],
  },
  "agent sessions list": {
    method: "GET",
    path: "/workspaces/{organizationId}/agent/sessions",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [
      {
        name: "issueId",
        flag: "issue",
      },
      {
        name: "limit",
        flag: "limit",
      },
    ],
    body: [],
  },
  "issues live": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues/{issueId}/live",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [],
  },
  "agent sessions get": {
    method: "GET",
    path: "/workspaces/{organizationId}/agent/sessions/{sessionId}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "sessionId",
        flag: "session",
      },
    ],
    query: [],
    body: [],
  },
  "agent sessions update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/agent/sessions/{sessionId}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "sessionId",
        flag: "session",
      },
    ],
    query: [],
    body: [
      {
        name: "status",
        flag: "status",
      },
      {
        name: "result",
        flag: "result",
      },
      {
        name: "url",
        flag: "url",
      },
    ],
  },
  "agent sessions activities": {
    method: "POST",
    path: "/workspaces/{organizationId}/agent/sessions/{sessionId}/activities",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "sessionId",
        flag: "session",
      },
    ],
    query: [],
    body: [
      {
        name: "type",
        flag: "type",
      },
      {
        name: "message",
        flag: "message",
      },
      {
        name: "payload",
        flag: "payload",
      },
    ],
  },
  "agent sessions poll create": {
    method: "POST",
    path: "/workspaces/{organizationId}/agent/sessions/{sessionId}/poll",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "sessionId",
        flag: "session",
      },
    ],
    query: [],
    body: [],
  },
  "agent providers list": {
    method: "GET",
    path: "/workspaces/{organizationId}/agent/providers",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "agent providers update": {
    method: "PUT",
    path: "/workspaces/{organizationId}/agent/providers/{agentId}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "agentId",
        flag: "agent-id",
      },
    ],
    query: [],
    body: [
      {
        name: "token",
        flag: "token",
      },
      {
        name: "providerOrgId",
        flag: "provider-org-id",
      },
      {
        name: "outpost",
        flag: "outpost",
      },
      {
        name: "outpostId",
        flag: "outpost-id",
      },
      {
        name: "outpostToken",
        flag: "outpost-token",
      },
      {
        name: "computeApiKey",
        flag: "compute-api-key",
      },
      {
        name: "computeApiUrl",
        flag: "compute-api-url",
      },
      {
        name: "computeSnapshot",
        flag: "compute-snapshot",
      },
      {
        name: "computeVolumeId",
        flag: "compute-volume-id",
      },
      {
        name: "config",
        flag: "config",
      },
    ],
  },
  "agent providers delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/agent/providers/{agentId}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "agentId",
        flag: "agent-id",
      },
    ],
    query: [],
    body: [],
  },
  "issues approvals": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues/{issueId}/approvals",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [
      {
        name: "approverId",
        flag: "approver",
      },
      {
        name: "comment",
        flag: "comment",
      },
    ],
  },
  "approvals respond": {
    method: "POST",
    path: "/workspaces/{organizationId}/approvals/{id}/respond",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "status",
        flag: "status",
      },
    ],
  },
  "issues activity": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues/{issueId}/activity",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [],
  },
  "projects list": {
    method: "GET",
    path: "/workspaces/{organizationId}/projects",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "projects create": {
    method: "POST",
    path: "/workspaces/{organizationId}/projects",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "description",
        flag: "description",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "startDate",
        flag: "start-date",
      },
      {
        name: "endDate",
        flag: "end-date",
      },
    ],
  },
  "projects get": {
    method: "GET",
    path: "/workspaces/{organizationId}/projects/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "projects update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/projects/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "description",
        flag: "description",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "startDate",
        flag: "start-date",
      },
      {
        name: "endDate",
        flag: "end-date",
      },
    ],
  },
  "projects delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/projects/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "cycles list": {
    method: "GET",
    path: "/workspaces/{organizationId}/cycles",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "cycles create": {
    method: "POST",
    path: "/workspaces/{organizationId}/cycles",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "projectId",
        flag: "project",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "number",
        flag: "number",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "autoRollover",
        flag: "auto-rollover",
      },
      {
        name: "startDate",
        flag: "start-date",
      },
      {
        name: "endDate",
        flag: "end-date",
      },
    ],
  },
  "cycles get": {
    method: "GET",
    path: "/workspaces/{organizationId}/cycles/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "cycles update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/cycles/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "projectId",
        flag: "project",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "number",
        flag: "number",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "autoRollover",
        flag: "auto-rollover",
      },
      {
        name: "startDate",
        flag: "start-date",
      },
      {
        name: "endDate",
        flag: "end-date",
      },
    ],
  },
  "cycles delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/cycles/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "cycles capacity list": {
    method: "GET",
    path: "/workspaces/{organizationId}/cycles/{id}/capacity",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "cycles rollover create": {
    method: "POST",
    path: "/workspaces/{organizationId}/cycles/rollover",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "labels list": {
    method: "GET",
    path: "/workspaces/{organizationId}/labels",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "labels create": {
    method: "POST",
    path: "/workspaces/{organizationId}/labels",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "color",
        flag: "color",
      },
    ],
  },
  "labels get": {
    method: "GET",
    path: "/workspaces/{organizationId}/labels/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "labels update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/labels/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "color",
        flag: "color",
      },
    ],
  },
  "labels delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/labels/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "memberships list": {
    method: "GET",
    path: "/workspaces/{organizationId}/memberships",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "memberships create": {
    method: "POST",
    path: "/workspaces/{organizationId}/memberships",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "userId",
        flag: "user",
      },
      {
        name: "role",
        flag: "role",
      },
    ],
  },
  "roadmaps list": {
    method: "GET",
    path: "/workspaces/{organizationId}/roadmaps",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "roadmaps create": {
    method: "POST",
    path: "/workspaces/{organizationId}/roadmaps",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "description",
        flag: "description",
      },
    ],
  },
  "roadmaps get": {
    method: "GET",
    path: "/workspaces/{organizationId}/roadmaps/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "roadmaps update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/roadmaps/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "description",
        flag: "description",
      },
    ],
  },
  "roadmaps delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/roadmaps/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  initiatives: {
    method: "POST",
    path: "/workspaces/{organizationId}/initiatives",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "roadmapId",
        flag: "roadmap",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "description",
        flag: "description",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "startDate",
        flag: "start-date",
      },
      {
        name: "targetDate",
        flag: "target-date",
      },
    ],
  },
  "roadmaps initiatives": {
    method: "GET",
    path: "/workspaces/{organizationId}/roadmaps/{id}/initiatives",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "initiatives get": {
    method: "GET",
    path: "/workspaces/{organizationId}/initiatives/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "initiatives update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/initiatives/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "roadmapId",
        flag: "roadmap",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "description",
        flag: "description",
      },
      {
        name: "status",
        flag: "status",
      },
      {
        name: "startDate",
        flag: "start-date",
      },
      {
        name: "targetDate",
        flag: "target-date",
      },
    ],
  },
  "initiatives delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/initiatives/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues comments": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues/{issueId}/comments",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [
      {
        name: "body",
        flag: "body",
      },
    ],
  },
  "issues comments get": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues comments update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "body",
        flag: "body",
      },
    ],
  },
  "issues comments delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/issues/{issueId}/comments/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues relations": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues/{issueId}/relations",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [
      {
        name: "toIssueId",
        flag: "to-issue-id",
      },
      {
        name: "type",
        flag: "type",
      },
    ],
  },
  "relations delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/relations/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues subscribers": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues/{issueId}/subscribers",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [
      {
        name: "linearUserId",
        flag: "linear-user-id",
      },
    ],
  },
  "issues subscribers delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/issues/{issueId}/subscribers/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues attachments": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues/{issueId}/attachments",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [],
  },
  "github users": {
    method: "POST",
    path: "/workspaces/{organizationId}/github/users",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "userId",
        flag: "user",
      },
      {
        name: "githubLogin",
        flag: "github-login",
      },
    ],
  },
  "github install": {
    method: "POST",
    path: "/workspaces/{organizationId}/github/install",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "installationId",
        flag: "installation",
      },
    ],
  },
  "github installations": {
    method: "GET",
    path: "/workspaces/{organizationId}/github/installations",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "github installations delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/github/installations/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "issues history": {
    method: "GET",
    path: "/workspaces/{organizationId}/issues/{issueId}/history",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "issueId",
        flag: "issue",
      },
    ],
    query: [],
    body: [],
  },
  "states list": {
    method: "GET",
    path: "/workspaces/{organizationId}/states",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "states create": {
    method: "POST",
    path: "/workspaces/{organizationId}/states",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "linearId",
        flag: "linear",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "type",
        flag: "type",
      },
      {
        name: "color",
        flag: "color",
      },
      {
        name: "position",
        flag: "position",
      },
    ],
  },
  "states get": {
    method: "GET",
    path: "/workspaces/{organizationId}/states/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "states update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/states/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "type",
        flag: "type",
      },
      {
        name: "color",
        flag: "color",
      },
      {
        name: "position",
        flag: "position",
      },
    ],
  },
  "states delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/states/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "webhook subscriptions list": {
    method: "GET",
    path: "/workspaces/{organizationId}/webhook-subscriptions",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "webhook subscriptions create": {
    method: "POST",
    path: "/workspaces/{organizationId}/webhook-subscriptions",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "url",
        flag: "url",
      },
      {
        name: "events",
        flag: "events",
      },
      {
        name: "secret",
        flag: "secret",
      },
    ],
  },
  "webhook subscriptions get": {
    method: "GET",
    path: "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "webhook subscriptions update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "url",
        flag: "url",
      },
      {
        name: "events",
        flag: "events",
      },
      {
        name: "secret",
        flag: "secret",
      },
    ],
  },
  "webhook subscriptions delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/webhook-subscriptions/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "webhook subscriptions deliveries": {
    method: "GET",
    path: "/workspaces/{organizationId}/webhook-subscriptions/{id}/deliveries",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "linear users list": {
    method: "GET",
    path: "/workspaces/{organizationId}/linear-users",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "linear users create": {
    method: "POST",
    path: "/workspaces/{organizationId}/linear-users",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "linearId",
        flag: "linear",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "email",
        flag: "email",
      },
    ],
  },
  "linear users get": {
    method: "GET",
    path: "/workspaces/{organizationId}/linear-users/{linearId}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "linearId",
        flag: "linear",
      },
    ],
    query: [],
    body: [],
  },
  "notifications list": {
    method: "GET",
    path: "/workspaces/{organizationId}/notifications",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [
      {
        name: "unreadOnly",
        flag: "unread-only",
      },
      {
        name: "snoozedOnly",
        flag: "snoozed-only",
      },
      {
        name: "includeSnoozed",
        flag: "include-snoozed",
      },
      {
        name: "limit",
        flag: "limit",
      },
    ],
    body: [],
  },
  "notifications unread count list": {
    method: "GET",
    path: "/workspaces/{organizationId}/notifications/unread-count",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "notifications read": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/notifications/{id}/read",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "notifications unread update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/notifications/{id}/unread",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "notifications snooze update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/notifications/{id}/snooze",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "until",
        flag: "until",
      },
    ],
  },
  "notifications mark all read create": {
    method: "POST",
    path: "/workspaces/{organizationId}/notifications/mark-all-read",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "issues reactions": {
    method: "POST",
    path: "/workspaces/{organizationId}/issues/{id}/reactions",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "emoji",
        flag: "emoji",
      },
    ],
  },
  "comments reactions": {
    method: "POST",
    path: "/workspaces/{organizationId}/comments/{commentId}/reactions",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "commentId",
        flag: "comment",
      },
    ],
    query: [],
    body: [
      {
        name: "emoji",
        flag: "emoji",
      },
    ],
  },
  "reactions delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/reactions/{reactionId}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "reactionId",
        flag: "reaction",
      },
    ],
    query: [],
    body: [],
  },
  "saved views list": {
    method: "GET",
    path: "/workspaces/{organizationId}/saved-views",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "saved views create": {
    method: "POST",
    path: "/workspaces/{organizationId}/saved-views",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "shared",
        flag: "shared",
      },
      {
        name: "filter",
        flag: "filter",
      },
      {
        name: "search",
        flag: "search",
      },
      {
        name: "sort",
        flag: "sort",
      },
      {
        name: "columns",
        flag: "columns",
      },
    ],
  },
  "saved views favorite create": {
    method: "POST",
    path: "/workspaces/{organizationId}/saved-views/{id}/favorite",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "saved views favorite delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/saved-views/{id}/favorite",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "me view preferences list": {
    method: "GET",
    path: "/workspaces/{organizationId}/me/view-preferences",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "me view preferences update": {
    method: "PUT",
    path: "/workspaces/{organizationId}/me/view-preferences",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "defaultViewId",
        flag: "default-view-id",
      },
    ],
  },
  "saved views get": {
    method: "GET",
    path: "/workspaces/{organizationId}/saved-views/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "saved views update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/saved-views/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "name",
        flag: "name",
      },
      {
        name: "shared",
        flag: "shared",
      },
      {
        name: "filter",
        flag: "filter",
      },
      {
        name: "search",
        flag: "search",
      },
      {
        name: "sort",
        flag: "sort",
      },
      {
        name: "columns",
        flag: "columns",
      },
    ],
  },
  "saved views delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/saved-views/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "teams list": {
    method: "GET",
    path: "/workspaces/{organizationId}/teams",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "teams create": {
    method: "POST",
    path: "/workspaces/{organizationId}/teams",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "key",
        flag: "key",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "isPublic",
        flag: "is-public",
      },
      {
        name: "parentAutoClose",
        flag: "parent-auto-close",
      },
      {
        name: "triageAssigneeId",
        flag: "triage-assignee-id",
      },
      {
        name: "defaultTemplateId",
        flag: "default-template-id",
      },
      {
        name: "subIssueAutoClose",
        flag: "sub-issue-auto-close",
      },
    ],
  },
  "teams get": {
    method: "GET",
    path: "/workspaces/{organizationId}/teams/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "teams update": {
    method: "PATCH",
    path: "/workspaces/{organizationId}/teams/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "key",
        flag: "key",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "isPublic",
        flag: "is-public",
      },
      {
        name: "parentAutoClose",
        flag: "parent-auto-close",
      },
      {
        name: "triageAssigneeId",
        flag: "triage-assignee-id",
      },
      {
        name: "defaultTemplateId",
        flag: "default-template-id",
      },
      {
        name: "subIssueAutoClose",
        flag: "sub-issue-auto-close",
      },
    ],
  },
  "teams delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/teams/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "teams members": {
    method: "POST",
    path: "/workspaces/{organizationId}/teams/{id}/members",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [
      {
        name: "memberId",
        flag: "member",
      },
      {
        name: "memberType",
        flag: "member-type",
      },
      {
        name: "role",
        flag: "role",
      },
    ],
  },
  "teams members delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/teams/{id}/members/{memberId}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
      {
        name: "memberId",
        flag: "member",
      },
    ],
    query: [
      {
        name: "memberType",
        flag: "member-type",
      },
    ],
    body: [],
  },
  "templates list": {
    method: "GET",
    path: "/workspaces/{organizationId}/templates",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "templates create": {
    method: "POST",
    path: "/workspaces/{organizationId}/templates",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "linearId",
        flag: "linear",
      },
      {
        name: "name",
        flag: "name",
      },
      {
        name: "templateData",
        flag: "template-data",
      },
    ],
  },
  "templates get": {
    method: "GET",
    path: "/workspaces/{organizationId}/templates/{id}",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
      {
        name: "id",
        flag: "id",
      },
    ],
    query: [],
    body: [],
  },
  "migrate linear": {
    method: "POST",
    path: "/workspaces/{organizationId}/migrate/linear",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "linearToken",
        flag: "linear-token",
      },
      {
        name: "teamId",
        flag: "team",
      },
    ],
  },
  export: {
    method: "GET",
    path: "/workspaces/{organizationId}/export",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  readiness: {
    method: "GET",
    path: "/workspaces/{organizationId}/readiness",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "slack list": {
    method: "GET",
    path: "/workspaces/{organizationId}/slack",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "slack delete": {
    method: "DELETE",
    path: "/workspaces/{organizationId}/slack",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "slack install create": {
    method: "POST",
    path: "/workspaces/{organizationId}/slack/install",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [],
  },
  "slack channel create": {
    method: "POST",
    path: "/workspaces/{organizationId}/slack/channel",
    params: [
      {
        name: "organizationId",
        flag: "workspace",
      },
    ],
    query: [],
    body: [
      {
        name: "channelId",
        flag: "channel-id",
      },
    ],
  },
};
