#!/usr/bin/env -S tsx
import { execFileSync } from "node:child_process";
import { pathToFileURL } from "node:url";

// Generated by contract:check — never hand-edited, so never tested directly.
const GENERATED = new Set([
  "src/mcp/mcp-tools.ts",
  "packages/cli/src/client/types.ts",
  "packages/cli/src/commands.ts",
  "src/assets/capture.iife.ts",
  "src/assets/chat.iife.ts",
  "src/assets/docs-bundle.ts",
  "src/agents/runner/bundle.ts",
]);

const EXPLANATION = /^[\s>*_-]*no tests:[*_\s]*(\S.*)$/im;

interface DiffCoverageReport {
  ok: boolean;
  reason: "no-source-changes" | "tests-changed" | "explained" | "missing-tests";
  sourceFiles: string[];
  testFiles: string[];
  /** Changed source files whose co-located `*.test.ts` was not touched. */
  untestedSourceFiles: string[];
  explanation: string | null;
}

export function isTestFile(file: string): boolean {
  return /\.(test|spec)\.tsx?$/.test(file) || /(^|\/)src\/test\//.test(file);
}

export function isSourceFile(file: string): boolean {
  return (
    /(^|\/)src\//.test(file) &&
    /\.tsx?$/.test(file) &&
    !file.endsWith(".d.ts") &&
    !isTestFile(file) &&
    !GENERATED.has(file)
  );
}

function siblingTests(file: string): string[] {
  const stem = file.replace(/\.tsx?$/, "");
  return [".test.ts", ".test.tsx", ".node.test.ts"].map((ext) => stem + ext);
}

export function findExplanation(prBody: string): string | null {
  const visible = prBody.replace(/<!--[\s\S]*?-->/g, "");
  const reason = EXPLANATION.exec(visible)?.[1]?.trim();
  return reason ? reason : null;
}

export function evaluateDiffCoverage(
  changedFiles: readonly string[],
  prBody: string
): DiffCoverageReport {
  const sourceFiles = changedFiles.filter(isSourceFile);
  const testFiles = changedFiles.filter(isTestFile);
  const changed = new Set(changedFiles);
  const untestedSourceFiles = sourceFiles.filter(
    (file) => !siblingTests(file).some((test) => changed.has(test))
  );
  const explanation = findExplanation(prBody);
  const base = { sourceFiles, testFiles, untestedSourceFiles, explanation };

  if (sourceFiles.length === 0) {
    return { ok: true, reason: "no-source-changes", ...base };
  }
  if (testFiles.length > 0)
    return { ok: true, reason: "tests-changed", ...base };
  if (explanation) return { ok: true, reason: "explained", ...base };
  return { ok: false, reason: "missing-tests", ...base };
}

function changedFilesSince(base: string): string[] {
  const output = execFileSync(
    "git",
    ["diff", "--name-only", "--diff-filter=ACMR", `${base}...HEAD`],
    { encoding: "utf8" }
  );
  return output.split("\n").filter((line) => line.length > 0);
}

function main(): void {
  const base = process.env.DIFF_COVERAGE_BASE ?? "origin/main";
  const report = evaluateDiffCoverage(
    changedFilesSince(base),
    process.env.PR_BODY ?? ""
  );

  if (report.untestedSourceFiles.length > 0) {
    console.log(
      "[diff-coverage] changed source files without a co-located test change:"
    );
    for (const file of report.untestedSourceFiles) console.log(`  - ${file}`);
  }
  if (!report.ok) {
    console.error(
      `[diff-coverage] ${report.sourceFiles.length} source file(s) under src/ changed but no *.test.ts did. ` +
        'Add or update tests, or explain why in the PR description with a line like "No tests: <reason>".'
    );
  }
  console.log(JSON.stringify({ proof: "diff-coverage", base, ...report }));
  if (!report.ok) process.exit(1);
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main();
}
