#!/usr/bin/env -S tsx
import { execSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");
const docsDir = resolve(repoRoot, "docs");
const outputPath = resolve(repoRoot, "src/assets/docs-bundle.ts");

const files = readdirSync(docsDir)
  .filter((f) => f.endsWith(".md"))
  .toSorted();

const entries = files.map(
  (f) =>
    `${JSON.stringify(f)}: ${JSON.stringify(readFileSync(resolve(docsDir, f), "utf8"))}`
);

writeFileSync(
  outputPath,
  `// Generated by scripts/generate-docs-bundle.ts — do not edit.\nexport const docsBundle: Record<string, string> = {\n${entries.join(",\n")},\n};\n`
);
execSync(`pnpm exec vp check --fix ${outputPath}`, { stdio: "ignore" });

console.log(`[docs-bundle] ${files.length} docs -> src/assets/docs-bundle.ts`);
