#!/usr/bin/env -S tsx
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");
const runnerDir = resolve(repoRoot, "src/agents/runner");
const outputPath = resolve(runnerDir, "bundle.ts");

const parts = ["core", "cursor", "devin", "codex", "claude"] as const;

const entries = parts.map(
  (name) =>
    `  ${name}: ${JSON.stringify(readFileSync(resolve(runnerDir, `${name}.py`), "utf8"))}`
);

writeFileSync(
  outputPath,
  `// Generated by scripts/generate-runner-bundle.ts — do not edit.\n// Edit the .py files in this directory, then run \`pnpm run runner:bundle\`.\nexport const runnerBundle = {\n${entries.join(",\n")},\n} as const;\n`
);
execSync(`pnpm exec vp check --fix ${outputPath}`, { stdio: "ignore" });

console.log(
  `[runner-bundle] ${parts.length} parts -> src/agents/runner/bundle.ts`
);
